import { redirect } from 'next/navigation'
import AdminShell from '@/components/growth-admin/AdminShell'
import { Badge, EmptyState, PageHeader, SectionHeading, StatCard, statusTone } from '@/components/growth-admin/AdminUi'
import { getTopCompanies, isGrowthAdminAuthenticated, queryGrowthTable } from '@/lib/growth-admin'

export const dynamic='force-dynamic'
export const revalidate=0

type Project={project_id:string;name:string;status:string}
type Invoice={invoice_id:string;company_id?:string|null;project_id?:string|null;invoice_number?:string;issue_date?:string;due_date?:string;currency:string;subtotal:number|string;tax:number|string;total:number|string;status:string;external_file_url?:string;created_at?:string}
type Expense={expense_id:string;project_id?:string|null;vendor?:string;category?:string;expense_date?:string;currency:string;total:number|string;status:string}
type Payment={payment_id:string;invoice_id?:string|null;company_id?:string|null;payment_date?:string;currency:string;amount:number|string;method?:string;reference?:string;status:string}
const n=(v:number|string|undefined)=>Number(v||0)

export default async function FinancePage(){
  if(!(await isGrowthAdminAuthenticated())) redirect('/growth-admin/login')
  const [companies,projects,invoices,expenses,payments]=await Promise.all([
    getTopCompanies(),
    queryGrowthTable<Project>('operations_projects',{order:'created_at.desc',limit:'200'}),
    queryGrowthTable<Invoice>('finance_invoices',{order:'created_at.desc',limit:'300'}),
    queryGrowthTable<Expense>('finance_expenses',{order:'created_at.desc',limit:'300'}),
    queryGrowthTable<Payment>('finance_payments',{order:'created_at.desc',limit:'300'}),
  ])
  const companyById=new Map(companies.map((c)=>[c.company_id,c]))
  const invoiced=invoices.reduce((s,r)=>s+n(r.total),0)
  const received=payments.reduce((s,r)=>s+n(r.amount),0)
  const spent=expenses.reduce((s,r)=>s+n(r.total),0)
  const outstanding=Math.max(0,invoiced-received)
  return <AdminShell active="finance">
    <PageHeader eyebrow="Finance OS" title="Finanzas" description="Base financiera vinculada al CRM: proyecto → cliente → factura → cobro, y proyecto → gasto. No sustituye aún a un software fiscal/contable, pero evita que la futura capa financiera nazca aislada."/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Facturado" value={`${invoiced.toLocaleString('es-ES')} €`} tone="blue"/><StatCard label="Cobrado" value={`${received.toLocaleString('es-ES')} €`} tone="green"/><StatCard label="Pendiente cobro" value={`${outstanding.toLocaleString('es-ES')} €`} tone="amber"/><StatCard label="Gastos" value={`${spent.toLocaleString('es-ES')} €`} tone="violet"/></div>

    <section className="mt-10"><SectionHeading eyebrow="Registro" title="Añadir movimiento" description="Primera capa operativa; posteriormente se añadirá OCR/documentos, conciliación e integración bancaria/fiscal."/><div className="grid gap-5 xl:grid-cols-3">
      <form action="/api/growth-admin/finance" method="post" className="rounded-2xl border border-slate-800 bg-slate-900/50 p-5"><input type="hidden" name="type" value="invoice"/><p className="font-semibold text-white">Nueva factura</p><select name="company_id" className="mt-4 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"><option value="">Cliente</option>{companies.map(c=><option key={c.company_id} value={c.company_id}>{c.name}</option>)}</select><select name="project_id" className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"><option value="">Proyecto opcional</option>{projects.map(p=><option key={p.project_id} value={p.project_id}>{p.name}</option>)}</select><input name="invoice_number" placeholder="Nº factura" className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><div className="mt-2 grid grid-cols-2 gap-2"><input type="date" name="issue_date" className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><input type="date" name="due_date" className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/></div><div className="mt-2 grid grid-cols-3 gap-2"><input name="subtotal" placeholder="Base" className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><input name="tax" placeholder="IVA" className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><input name="total" placeholder="Total" className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/></div><button className="mt-3 rounded-lg bg-white px-4 py-2 text-sm font-semibold text-slate-950">Registrar factura</button></form>
      <form action="/api/growth-admin/finance" method="post" className="rounded-2xl border border-slate-800 bg-slate-900/50 p-5"><input type="hidden" name="type" value="expense"/><p className="font-semibold text-white">Nuevo gasto</p><select name="project_id" className="mt-4 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"><option value="">Proyecto opcional</option>{projects.map(p=><option key={p.project_id} value={p.project_id}>{p.name}</option>)}</select><input name="vendor" placeholder="Proveedor" className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><input name="category" placeholder="Categoría" className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><input type="date" name="expense_date" className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><div className="mt-2 grid grid-cols-3 gap-2"><input name="subtotal" placeholder="Base" className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><input name="tax" placeholder="IVA" className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><input name="total" placeholder="Total" className="rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/></div><button className="mt-3 rounded-lg bg-white px-4 py-2 text-sm font-semibold text-slate-950">Registrar gasto</button></form>
      <form action="/api/growth-admin/finance" method="post" className="rounded-2xl border border-slate-800 bg-slate-900/50 p-5"><input type="hidden" name="type" value="payment"/><p className="font-semibold text-white">Registrar cobro</p><select name="invoice_id" className="mt-4 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"><option value="">Factura</option>{invoices.map(i=><option key={i.invoice_id} value={i.invoice_id}>{i.invoice_number||i.invoice_id} · {n(i.total)} {i.currency}</option>)}</select><select name="company_id" className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"><option value="">Cliente</option>{companies.map(c=><option key={c.company_id} value={c.company_id}>{c.name}</option>)}</select><input type="date" name="payment_date" className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><input name="amount" placeholder="Importe" className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><input name="method" placeholder="Método / banco" className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><input name="reference" placeholder="Referencia" className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><button className="mt-3 rounded-lg bg-white px-4 py-2 text-sm font-semibold text-slate-950">Registrar cobro</button></form>
    </div></section>

    <section className="mt-12"><SectionHeading eyebrow="Accounts receivable" title="Facturas" count={invoices.length}/>{invoices.length===0?<EmptyState>No hay facturas registradas todavía.</EmptyState>:<div className="overflow-x-auto rounded-xl border border-slate-800"><table className="min-w-full text-left text-xs"><thead className="bg-slate-950 text-slate-600"><tr><th className="px-4 py-3">Factura</th><th className="px-4 py-3">Cliente</th><th className="px-4 py-3">Emisión</th><th className="px-4 py-3">Vence</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">Estado</th></tr></thead><tbody>{invoices.map(i=><tr key={i.invoice_id} className="border-t border-slate-800 bg-slate-900/40"><td className="px-4 py-3 text-slate-200">{i.invoice_number||i.invoice_id}</td><td className="px-4 py-3">{i.company_id?companyById.get(i.company_id)?.name||'—':'—'}</td><td className="px-4 py-3">{i.issue_date||'—'}</td><td className="px-4 py-3">{i.due_date||'—'}</td><td className="px-4 py-3">{n(i.total).toLocaleString('es-ES')} {i.currency}</td><td className="px-4 py-3"><Badge tone={statusTone(i.status)}>{i.status}</Badge></td></tr>)}</tbody></table></div>}</section>

    <section className="mt-12 pb-12"><div className="grid gap-6 xl:grid-cols-2"><div><SectionHeading eyebrow="Costs" title="Gastos" count={expenses.length}/>{expenses.length===0?<EmptyState>Sin gastos registrados.</EmptyState>:<div className="space-y-2">{expenses.slice(0,30).map(e=><div key={e.expense_id} className="flex items-center justify-between rounded-xl border border-slate-800 p-4"><div><p className="text-sm text-white">{e.vendor||e.category||'Gasto'}</p><p className="text-xs text-slate-600">{e.expense_date||'—'} · {e.category||'Sin categoría'}</p></div><p className="font-semibold">{n(e.total).toLocaleString('es-ES')} {e.currency}</p></div>)}</div>}</div><div><SectionHeading eyebrow="Cash" title="Cobros" count={payments.length}/>{payments.length===0?<EmptyState>Sin cobros registrados.</EmptyState>:<div className="space-y-2">{payments.slice(0,30).map(p=><div key={p.payment_id} className="flex items-center justify-between rounded-xl border border-slate-800 p-4"><div><p className="text-sm text-white">{p.reference||p.method||'Cobro'}</p><p className="text-xs text-slate-600">{p.payment_date||'—'}</p></div><p className="font-semibold text-emerald-300">{n(p.amount).toLocaleString('es-ES')} {p.currency}</p></div>)}</div>}</div></div></section>
  </AdminShell>
}
