import { redirect } from 'next/navigation'
import AdminShell from '@/components/growth-admin/AdminShell'
import { Badge, EmptyState, PageHeader, SectionHeading, StatCard, adminButtonPrimary, adminInput, adminPanel, statusTone } from '@/components/growth-admin/AdminUi'
import { getTopCompanies, isGrowthAdminAuthenticated, queryGrowthTable } from '@/lib/growth-admin'

export const dynamic='force-dynamic'
export const revalidate=0

type Project={project_id:string;name:string;status:string}
type Invoice={invoice_id:string;company_id?:string|null;project_id?:string|null;invoice_number?:string;issue_date?:string;due_date?:string;currency:string;subtotal:number|string;tax:number|string;total:number|string;status:string;external_file_url?:string;created_at?:string}
type Expense={expense_id:string;project_id?:string|null;vendor?:string;category?:string;expense_date?:string;currency:string;total:number|string;status:string}
type Payment={payment_id:string;invoice_id?:string|null;company_id?:string|null;payment_date?:string;currency:string;amount:number|string;method?:string;reference?:string;status:string}
const n=(v:number|string|undefined)=>Number(v||0)

export default async function FinancePage(){
  if(!(await isGrowthAdminAuthenticated())) redirect('/growth-admin/login')
  const [companies,projects,invoices,expenses,payments]=await Promise.all([
    getTopCompanies(),
    queryGrowthTable<Project>('operations_projects',{order:'created_at.desc',limit:'200'}),
    queryGrowthTable<Invoice>('finance_invoices',{order:'created_at.desc',limit:'300'}),
    queryGrowthTable<Expense>('finance_expenses',{order:'created_at.desc',limit:'300'}),
    queryGrowthTable<Payment>('finance_payments',{order:'created_at.desc',limit:'300'}),
  ])
  const companyById=new Map(companies.map((c)=>[c.company_id,c]))
  const invoiced=invoices.reduce((s,r)=>s+n(r.total),0)
  const received=payments.reduce((s,r)=>s+n(r.amount),0)
  const spent=expenses.reduce((s,r)=>s+n(r.total),0)
  const outstanding=Math.max(0,invoiced-received)

  return <AdminShell active="finance">
    <PageHeader eyebrow="CRM · Finance" title="Finanzas" description="La capa financiera pertenece al mismo CRM: cliente → oportunidad → proyecto → factura → cobro, y proyecto → gasto. Esto evita una contabilidad operativa aislada del contexto comercial."/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Facturado" value={`${invoiced.toLocaleString('es-ES')} €`} tone="blue"/><StatCard label="Cobrado" value={`${received.toLocaleString('es-ES')} €`} tone="green"/><StatCard label="Pendiente cobro" value={`${outstanding.toLocaleString('es-ES')} €`} tone="amber"/><StatCard label="Gastos" value={`${spent.toLocaleString('es-ES')} €`} tone="violet"/></div>

    <section className="mt-12 rounded-3xl border border-indigo-100 bg-indigo-50/60 p-5 md:p-7"><SectionHeading eyebrow="CRM · Registro financiero" title="Añadir movimiento" description="Primera capa operativa. Después añadiremos documentos, OCR, conciliación, impuestos e integraciones, conservando siempre relación con cliente y proyecto."/><div className="grid gap-5 xl:grid-cols-3">
      <form action="/api/growth-admin/finance" method="post" className={`${adminPanel} p-5`}><input type="hidden" name="type" value="invoice"/><p className="font-semibold text-slate-950">Nueva factura</p><select name="company_id" className={`mt-4 w-full ${adminInput}`}><option value="">Cliente</option>{companies.map(c=><option key={c.company_id} value={c.company_id}>{c.name}</option>)}</select><select name="project_id" className={`mt-2 w-full ${adminInput}`}><option value="">Proyecto opcional</option>{projects.map(p=><option key={p.project_id} value={p.project_id}>{p.name}</option>)}</select><input name="invoice_number" placeholder="Nº factura" className={`mt-2 w-full ${adminInput}`}/><div className="mt-2 grid grid-cols-2 gap-2"><input type="date" name="issue_date" className={adminInput}/><input type="date" name="due_date" className={adminInput}/></div><div className="mt-2 grid grid-cols-3 gap-2"><input name="subtotal" placeholder="Base" className={adminInput}/><input name="tax" placeholder="IVA" className={adminInput}/><input name="total" placeholder="Total" className={adminInput}/></div><button className={`mt-3 ${adminButtonPrimary}`}>Registrar factura</button></form>
      <form action="/api/growth-admin/finance" method="post" className={`${adminPanel} p-5`}><input type="hidden" name="type" value="expense"/><p className="font-semibold text-slate-950">Nuevo gasto</p><select name="project_id" className={`mt-4 w-full ${adminInput}`}><option value="">Proyecto opcional</option>{projects.map(p=><option key={p.project_id} value={p.project_id}>{p.name}</option>)}</select><input name="vendor" placeholder="Proveedor" className={`mt-2 w-full ${adminInput}`}/><input name="category" placeholder="Categoría" className={`mt-2 w-full ${adminInput}`}/><input type="date" name="expense_date" className={`mt-2 w-full ${adminInput}`}/><div className="mt-2 grid grid-cols-3 gap-2"><input name="subtotal" placeholder="Base" className={adminInput}/><input name="tax" placeholder="IVA" className={adminInput}/><input name="total" placeholder="Total" className={adminInput}/></div><button className={`mt-3 ${adminButtonPrimary}`}>Registrar gasto</button></form>
      <form action="/api/growth-admin/finance" method="post" className={`${adminPanel} p-5`}><input type="hidden" name="type" value="payment"/><p className="font-semibold text-slate-950">Registrar cobro</p><select name="invoice_id" className={`mt-4 w-full ${adminInput}`}><option value="">Factura</option>{invoices.map(i=><option key={i.invoice_id} value={i.invoice_id}>{i.invoice_number||i.invoice_id} · {n(i.total)} {i.currency}</option>)}</select><select name="company_id" className={`mt-2 w-full ${adminInput}`}><option value="">Cliente</option>{companies.map(c=><option key={c.company_id} value={c.company_id}>{c.name}</option>)}</select><input type="date" name="payment_date" className={`mt-2 w-full ${adminInput}`}/><input name="amount" placeholder="Importe" className={`mt-2 w-full ${adminInput}`}/><input name="method" placeholder="Método / banco" className={`mt-2 w-full ${adminInput}`}/><input name="reference" placeholder="Referencia" className={`mt-2 w-full ${adminInput}`}/><button className={`mt-3 ${adminButtonPrimary}`}>Registrar cobro</button></form>
    </div></section>

    <section className="mt-14"><SectionHeading eyebrow="CRM · Accounts receivable" title="Facturas" description="Las facturas mantienen vínculo con cliente y proyecto para que el CRM pueda calcular pipeline, revenue y cobro real." count={invoices.length}/>{invoices.length===0?<EmptyState>No hay facturas registradas todavía.</EmptyState>:<div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-[0_1px_2px_rgba(15,23,42,0.04)]"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-4 py-3">Factura</th><th className="px-4 py-3">Cliente</th><th className="px-4 py-3">Emisión</th><th className="px-4 py-3">Vence</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">Estado</th></tr></thead><tbody>{invoices.map(i=><tr key={i.invoice_id} className="border-t border-slate-200"><td className="px-4 py-3 font-medium text-slate-800">{i.invoice_number||i.invoice_id}</td><td className="px-4 py-3 text-slate-600">{i.company_id?companyById.get(i.company_id)?.name||'—':'—'}</td><td className="px-4 py-3 text-slate-600">{i.issue_date||'—'}</td><td className="px-4 py-3 text-slate-600">{i.due_date||'—'}</td><td className="px-4 py-3 font-semibold text-slate-900">{n(i.total).toLocaleString('es-ES')} {i.currency}</td><td className="px-4 py-3"><Badge tone={statusTone(i.status)}>{i.status}</Badge></td></tr>)}</tbody></table></div>}</section>

    <section className="mt-14 pb-12"><div className="grid gap-8 xl:grid-cols-2"><div><SectionHeading eyebrow="CRM · Costs" title="Gastos" count={expenses.length}/>{expenses.length===0?<EmptyState>Sin gastos registrados.</EmptyState>:<div className="space-y-3">{expenses.slice(0,30).map(e=><div key={e.expense_id} className={`${adminPanel} flex items-center justify-between p-4`}><div><p className="text-sm font-semibold text-slate-950">{e.vendor||e.category||'Gasto'}</p><p className="text-xs text-slate-500">{e.expense_date||'—'} · {e.category||'Sin categoría'}</p></div><p className="font-semibold text-slate-950">{n(e.total).toLocaleString('es-ES')} {e.currency}</p></div>)}</div>}</div><div><SectionHeading eyebrow="CRM · Cash" title="Cobros" count={payments.length}/>{payments.length===0?<EmptyState>Sin cobros registrados.</EmptyState>:<div className="space-y-3">{payments.slice(0,30).map(p=><div key={p.payment_id} className={`${adminPanel} flex items-center justify-between p-4`}><div><p className="text-sm font-semibold text-slate-950">{p.reference||p.method||'Cobro'}</p><p className="text-xs text-slate-500">{p.payment_date||'—'}</p></div><p className="font-semibold text-emerald-700">{n(p.amount).toLocaleString('es-ES')} {p.currency}</p></div>)}</div>}</div></div></section>
  </AdminShell>
}
