import { redirect } from 'next/navigation'
import AdminShell from '@/components/growth-admin/AdminShell'
import { Badge, EmptyState, PageHeader, SectionHeading, StatCard, adminButtonPrimary, adminButtonSecondary, adminInput, adminPanel, statusTone } from '@/components/growth-admin/AdminUi'
import { isGrowthAdminAuthenticated } from '@/lib/growth-admin'
import { getDealDeskBundle, getOperationsBundle } from '@/lib/growth-admin-performance'

export const dynamic = 'force-dynamic'
type Project={project_id:string;company_id?:string|null;opportunity_id?:string|null;name:string;status:string;owner?:string;start_date?:string;end_date?:string;budget:number|string;currency:string;created_at?:string}
type Task={task_id:string;type:string;scheduled_for?:string|null;status:string;requires_approval?:boolean;inputs?:Record<string,unknown>|null;outputs?:Record<string,unknown>|null;created_at?:string}
type Params={task?:string;project?:string}
const money=(value:unknown,currency='EUR')=>new Intl.NumberFormat('es-ES',{style:'currency',currency:currency||'EUR',maximumFractionDigits:0}).format(Number(value||0))

export default async function OperationsPage({searchParams}:{searchParams?:Promise<Params>}){
  if(!(await isGrowthAdminAuthenticated())) redirect('/growth-admin/login')
  const params=searchParams?await searchParams:{}
  const [bundle,deals]=await Promise.all([getOperationsBundle(),getDealDeskBundle()])
  const tasks=bundle.tasks as unknown as Task[]
  const projects=bundle.projects as unknown as Project[]
  const companies=bundle.companies
  const opportunities=deals.opportunities
  const companyById=new Map(companies.map(c=>[c.company_id,c]))
  const openTasks=tasks.filter(t=>!['completed','done','executed'].includes(t.status))
  const failed=tasks.filter(t=>t.status==='failed')
  const operator=tasks.filter(t=>t.type.startsWith('OPERATOR_'))
  const activeDeals=opportunities.filter(item=>!['won','lost'].includes(String(item.stage||'')))
  const wonDeals=opportunities.filter(item=>String(item.stage||'')==='won')
  const projectOpportunityIds=new Set(projects.map(item=>String(item.opportunity_id||'')).filter(Boolean))
  const convertible=wonDeals.filter(item=>!projectOpportunityIds.has(String(item.opportunity_id)))
  const selectedTaskId=String(params.task||'')
  const selectedTask=selectedTaskId?tasks.find(task=>task.task_id===selectedTaskId):undefined
  const selectedProjectId=String(params.project||'')

  return <AdminShell active="operations">
    <PageHeader eyebrow="CRM · Operations" title="Operaciones" description="El trabajo operativo empieza antes del delivery: deals activos, conversión a proyecto, ejecución, knowledge y automatizaciones viven en el mismo hub." actions={<a href="/growth-admin/deal-desk" className={adminButtonPrimary}>Abrir Deal Desk</a>}/>
    {bundle.degraded&&<div className="mb-6 rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4 text-sm text-amber-800">Operaciones ha cargado en modo seguro porque una consulta tardó demasiado.</div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Deals activos" value={activeDeals.length} tone="violet"/><StatCard label="Delivery" value={projects.filter(p=>p.status==='active').length} tone="green"/><StatCard label="Tareas abiertas" value={openTasks.length} tone="blue"/><StatCard label="Fallos" value={failed.length} tone={failed.length?'amber':'green'}/></div>

    <section id="deals" className="mt-10"><SectionHeading eyebrow="Operaciones · Comercial" title="Deals activos" description="Clientes con una operación comercial en marcha. Abre el expediente para qualification, discovery, proposal, budget y negociación." count={activeDeals.length}/>{activeDeals.length===0?<EmptyState>No hay deals comerciales activos.</EmptyState>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{activeDeals.map(deal=>{const meta=(deal.metadata||{}) as Record<string,unknown>;return <article key={deal.opportunity_id} className={`${adminPanel} p-5`}><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-slate-950">{deal.company_name||deal.name}</p><p className="mt-1 text-xs text-slate-500">{String(meta.requested_service||meta.recommended_service||deal.recommended_service||'Servicio por definir')}</p></div><Badge tone={statusTone(deal.stage)}>{deal.stage}</Badge></div><div className="mt-4 grid grid-cols-3 gap-2 text-xs"><div><p className="text-slate-400">Prob.</p><p className="font-semibold">{Number(deal.probability||0)}%</p></div><div><p className="text-slate-400">Valor</p><p className="font-semibold">{money(deal.value,deal.currency)}</p></div><div><p className="text-slate-400">Origen</p><p className="truncate font-semibold">{String(meta.origin||deal.source||'—')}</p></div></div><div className="mt-4 flex gap-2"><a href={`/growth-admin/deal-desk?opportunity=${encodeURIComponent(deal.opportunity_id)}`} className={adminButtonPrimary}>Abrir expediente</a></div></article>})}</div>}</section>

    {convertible.length>0&&<section className="mt-10 rounded-3xl border border-emerald-200 bg-emerald-50/70 p-5"><SectionHeading eyebrow="Handoff" title="Deals ganados pendientes de delivery" description="Ya no hace falta reescribir cliente, presupuesto o moneda: crea el proyecto directamente desde el deal." count={convertible.length}/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{convertible.map(deal=><form key={deal.opportunity_id} action="/api/growth-admin/project" method="post" className="rounded-2xl border border-emerald-200 bg-white p-4"><input type="hidden" name="opportunity_id" value={deal.opportunity_id}/><input type="hidden" name="status" value="active"/><p className="text-sm font-semibold text-slate-900">{deal.company_name||deal.name}</p><p className="mt-1 text-xs text-slate-500">{money(deal.value,deal.currency)} · {deal.currency||'EUR'}</p><button className="mt-3 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Crear proyecto de delivery</button></form>)}</div></section>}

    <section id="delivery" className="mt-12"><SectionHeading eyebrow="Operaciones · Delivery" title="Proyectos" description="Proyectos ganados o internos ya en ejecución. La oportunidad original se conserva enlazada." count={projects.length}/>{projects.length===0?<EmptyState>No hay proyectos todavía. Los deals ganados pueden convertirse aquí automáticamente.</EmptyState>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.map(p=><article id={`project-${p.project_id}`} key={p.project_id} className={`${adminPanel} p-5 ${selectedProjectId===p.project_id?'ring-2 ring-violet-200':''}`}><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-slate-950">{p.name}</p><p className="mt-1 text-xs text-slate-500">{p.company_id?companyById.get(p.company_id)?.name||'Cliente':'Interno'} · {p.owner||'Sin owner'}</p></div><Badge tone={statusTone(p.status)}>{p.status}</Badge></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs text-slate-500"><span>{p.start_date||'—'} → {p.end_date||'—'}</span><span className="text-right font-medium text-slate-700">{money(p.budget,p.currency)}</span></div>{p.opportunity_id&&<a href={`/growth-admin/deal-desk?opportunity=${encodeURIComponent(p.opportunity_id)}`} className="mt-3 inline-block text-xs font-semibold text-violet-700">Ver deal origen →</a>}</article>)}</div>}</section>

    <details className={`${adminPanel} mt-10 p-5`}><summary className="cursor-pointer text-sm font-semibold text-slate-900">Crear proyecto manual / interno</summary><form action="/api/growth-admin/project" method="post" className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><input name="name" required placeholder="Nombre del proyecto" className={adminInput}/><select name="company_id" className={adminInput}><option value="">Cliente</option>{companies.map(c=><option key={c.company_id} value={c.company_id}>{c.name}</option>)}</select><input name="owner" placeholder="Owner" className={adminInput}/><select name="currency" defaultValue="EUR" className={adminInput}><option>EUR</option><option>USD</option></select><input type="date" name="start_date" className={adminInput}/><input type="date" name="end_date" className={adminInput}/><input name="budget" placeholder="Budget" className={adminInput}/><div className="flex gap-2"><select name="status" className={`min-w-0 flex-1 ${adminInput}`}><option value="planned">Planned</option><option value="active">Active</option><option value="paused">Paused</option></select><button className={adminButtonPrimary}>Crear</button></div></form></details>

    <section id="knowledge" className="mt-14"><SectionHeading eyebrow="CRM · Knowledge" title="Documentación y herramientas" description="Documentación, SOPs, plantillas e integraciones operativas."/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><a href="https://drive.google.com/" target="_blank" rel="noreferrer" className={`${adminPanel} p-5 transition hover:-translate-y-0.5 hover:shadow-md`}><p className="font-semibold text-slate-950">Google Drive ↗</p><p className="mt-2 text-sm leading-6 text-slate-500">Repositorio documental. La cuenta corporativa se configurará en la tanda de integraciones.</p></a><div className={`${adminPanel} p-5`}><p className="font-semibold text-slate-950">SOPs y manuales</p><p className="mt-2 text-sm leading-6 text-slate-500">Procesos repetibles, checklist y documentación de delivery.</p></div><div className={`${adminPanel} p-5`}><p className="font-semibold text-slate-950">Plantillas y assets</p><p className="mt-2 text-sm leading-6 text-slate-500">Proposals, budgets, informes y entregables reutilizables.</p></div><a href="/growth-admin/system" className={`${adminPanel} p-5 transition hover:-translate-y-0.5 hover:shadow-md`}><p className="font-semibold text-slate-950">Integraciones</p><p className="mt-2 text-sm leading-6 text-slate-500">Drive, Gmail, LinkedIn, GA4, workers y conectores.</p></a></div></section>

    {selectedTask&&<section className="mt-12 rounded-2xl border border-violet-200 bg-violet-50 p-5"><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase text-violet-600">Trazabilidad seleccionada</p><h2 className="mt-1 font-semibold">{selectedTask.type}</h2></div><Badge tone={statusTone(selectedTask.status)}>{selectedTask.status}</Badge></div><div className="mt-3 grid gap-3 lg:grid-cols-2"><pre className="overflow-auto rounded-xl bg-white p-3 text-[10px]">{JSON.stringify(selectedTask.inputs||{},null,2)}</pre><pre className="overflow-auto rounded-xl bg-white p-3 text-[10px]">{JSON.stringify(selectedTask.outputs||{},null,2)}</pre></div></section>}

    <section className="mt-14 pb-12"><SectionHeading eyebrow="CRM · Automation" title="Tareas y agentes" description="Histórico técnico auditable; plegado para no ocupar el espacio operativo principal." count={tasks.length}/><details className={adminPanel}><summary className="cursor-pointer p-4 text-sm font-semibold text-slate-800">Ver histórico ({tasks.length}) · {operator.length} operator runs</summary><div className="overflow-x-auto border-t border-slate-200"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-4 py-3">Estado</th><th className="px-4 py-3">Tipo</th><th className="px-4 py-3">Creada</th></tr></thead><tbody>{tasks.slice(0,100).map(t=><tr key={t.task_id} className="border-t border-slate-100"><td className="px-4 py-3"><Badge tone={statusTone(t.status)}>{t.status}</Badge></td><td className="px-4 py-3 font-medium">{t.type}</td><td className="px-4 py-3 text-slate-500">{t.created_at||'—'}</td></tr>)}</tbody></table></div></details></section>
  </AdminShell>
}
