import { redirect } from 'next/navigation'
import AdminShell from '@/components/growth-admin/AdminShell'
import { EmptyState, PageHeader, SectionHeading, StatCard, adminButtonPrimary, adminButtonSecondary, adminPanel } from '@/components/growth-admin/AdminUi'
import { getLinkedInAnalyticsImports, getLinkedInPostMetrics, getRecentContent, getWebAnalyticsDaily, isGrowthAdminAuthenticated } from '@/lib/growth-admin'
import { queryGrowthTable } from '@/lib/supabase-growth'
import { getMetricsBundle } from '@/lib/growth-admin-performance'
import { gmailOAuthReadiness } from '@/lib/google-oauth-finance'

export const dynamic='force-dynamic'
export const revalidate=0

type SeoRow={metric_id:string;metric_date:string;query:string;page:string;country:string;device:string;clicks:number|string;impressions:number|string;ctr:number|string;position:number|string}
function sum(rows:Array<Record<string,unknown>>,key:string){return rows.reduce((total,row)=>total+Number(row[key]||0),0)}
function ratio(n:number,d:number){return d>0?`${((n/d)*100).toFixed(2)}%`:'—'}
function euro(v:unknown){return `${Number(v||0).toLocaleString('es-ES',{maximumFractionDigits:0})} €`}

export default async function AnalyticsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  if(!(await isGrowthAdminAuthenticated())) redirect('/growth-admin/login')
  const params=await searchParams
  const [linkedin,imports,web,content,seo,integrated]=await Promise.all([
    getLinkedInPostMetrics(),getLinkedInAnalyticsImports(),getWebAnalyticsDaily(),getRecentContent(),
    queryGrowthTable<SeoRow>('search_console_daily',{tenant_id:'eq.sc-analytics',order:'metric_date.desc',limit:'5000'},{cacheSeconds:5}),getMetricsBundle(),
  ])
  const oauth=gmailOAuthReadiness()
  const contentById=new Map(content.map((item)=>[item.content_id,item]))
  const account=typeof params.account==='string'&&params.account==='sc_analytics'?'sc_analytics':'arnau'
  const liRows=linkedin.filter((row)=>row.account_type===account)
  const latestByContent=new Map<string,(typeof liRows)[number]>()
  liRows.forEach((row)=>{const key=row.content_id||row.external_post_id||row.external_post_url||row.metric_id;if(!latestByContent.has(key))latestByContent.set(key,row)})
  const latest=[...latestByContent.values()]
  const impressions=sum(latest as unknown as Array<Record<string,unknown>>,'impressions'),reach=sum(latest as unknown as Array<Record<string,unknown>>,'reach'),reactions=sum(latest as unknown as Array<Record<string,unknown>>,'reactions'),comments=sum(latest as unknown as Array<Record<string,unknown>>,'comments'),saves=sum(latest as unknown as Array<Record<string,unknown>>,'saves'),clicks=sum(latest as unknown as Array<Record<string,unknown>>,'clicks'),followers=sum(latest as unknown as Array<Record<string,unknown>>,'followers_gained'),profileViews=sum(latest as unknown as Array<Record<string,unknown>>,'profile_views')
  const engagements=reactions+comments+sum(latest as unknown as Array<Record<string,unknown>>,'reposts')+saves+clicks
  const scope=(row:(typeof web)[number])=>String(row.metadata?.scope||'')
  const periodTotal=web.find((row)=>scope(row)==='period_total')
  const periodEvents=web.filter((row)=>scope(row)==='period_event')
  const acquisition=web.filter((row)=>scope(row)==='acquisition')
  const webTotals={sessions:Number(periodTotal?.sessions||0),engaged:Number(periodTotal?.engaged_sessions||0),views:Number(periodTotal?.page_views||0),events:Number(periodTotal?.key_events||0),discovery:sum(periodEvents as unknown as Array<Record<string,unknown>>,'discovery_clicks'),bookings:sum(periodEvents as unknown as Array<Record<string,unknown>>,'bookings')}
  const sourceMap=new Map<string,{sessions:number;engaged:number;views:number}>()
  acquisition.forEach((row)=>{const key=`${row.source||'(direct)'} / ${row.medium||'(none)'}`,current=sourceMap.get(key)||{sessions:0,engaged:0,views:0};current.sessions+=Number(row.sessions||0);current.engaged+=Number(row.engaged_sessions||0);current.views+=Number(row.page_views||0);sourceMap.set(key,current)})
  const topSources=[...sourceMap.entries()].sort((a,b)=>b[1].sessions-a[1].sessions).slice(0,12)
  const queryMap=new Map<string,{clicks:number;impressions:number;positionWeighted:number}>()
  seo.forEach((row)=>{const key=row.query||'(sin query)',current=queryMap.get(key)||{clicks:0,impressions:0,positionWeighted:0};const imp=Number(row.impressions||0);current.clicks+=Number(row.clicks||0);current.impressions+=imp;current.positionWeighted+=Number(row.position||0)*imp;queryMap.set(key,current)})
  const topQueries=[...queryMap.entries()].sort((a,b)=>b[1].impressions-a[1].impressions).slice(0,20)
  const imported=typeof params.imported==='string'?params.imported:''

  return <AdminShell active="analytics">
    <PageHeader eyebrow="Métricas · Intelligence" title="Analytics" description="Detalle interno por fuente. GA4, Search Console, LinkedIn, funnel comercial y finanzas convergen en Supabase; los enlaces externos dejan de ser necesarios para el seguimiento rutinario." actions={<>{integrated.sources.google_connected?<form action="/api/growth-admin/metrics/sync" method="post"><input type="hidden" name="days" value="365"/><input type="hidden" name="return_to" value="/growth-admin/analytics"/><button className="rounded-lg bg-white px-4 py-2.5 text-sm font-semibold text-slate-950">Sincronizar Google</button></form>:oauth.configured?<a href="/api/growth-admin/google/connect?account=corporate&return_to=/growth-admin/analytics" className="rounded-lg bg-white px-4 py-2.5 text-sm font-semibold text-slate-950">Conectar Google</a>:null}<a href="/growth-admin/metrics" className="rounded-lg border border-white/20 bg-white/10 px-4 py-2.5 text-sm font-semibold text-white">← Cuadro de métricas</a></>}/>
    {imported&&<div className="mb-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">Importación LinkedIn completada: {imported} filas normalizadas y disponibles en el CRM.</div>}

    <div className="mb-8 flex flex-wrap gap-2"><a href="/growth-admin/analytics?account=arnau" className={`rounded-full border px-4 py-2 text-xs font-semibold ${account==='arnau'?'border-indigo-200 bg-indigo-50 text-indigo-700':'border-slate-200 bg-white text-slate-500'}`}>LinkedIn · Arnau</a><a href="/growth-admin/analytics?account=sc_analytics" className={`rounded-full border px-4 py-2 text-xs font-semibold ${account==='sc_analytics'?'border-indigo-200 bg-indigo-50 text-indigo-700':'border-slate-200 bg-white text-slate-500'}`}>LinkedIn · SC-Analytics</a><a href="#website" className="rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-500">Website · GA4</a><a href="#seo" className="rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-500">SEO · Search Console</a><a href="#business" className="rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-semibold text-slate-500">Negocio</a></div>

    <SectionHeading eyebrow="LinkedIn performance" title={account==='arnau'?'Arnau Sastre':'SC-Analytics'} description="La publicación es oficial vía API. Para analítica usamos el export oficial XLSX de rendimiento de contenido mientras LinkedIn mantenga restringido el acceso analítico; el análisis posterior queda íntegramente dentro del CRM."/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><StatCard label="Impressions" value={impressions.toLocaleString('es-ES')}/><StatCard label="Reach" value={reach.toLocaleString('es-ES')}/><StatCard label="Engagement" value={ratio(engagements,reach||impressions)} tone="blue"/><StatCard label="Saves" value={saves.toLocaleString('es-ES')} tone="violet"/><StatCard label="Clicks" value={clicks.toLocaleString('es-ES')} tone="green"/><StatCard label="Followers" value={followers.toLocaleString('es-ES')} tone="green"/></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><form action="/api/growth-admin/linkedin-analytics-import" method="post" encType="multipart/form-data" className={`${adminPanel} p-5`}><input type="hidden" name="account_type" value={account}/><input type="hidden" name="report_type" value="content"/><p className="text-sm font-semibold text-slate-950">Importar rendimiento de contenido</p><p className="mt-2 text-xs leading-5 text-slate-500">Sube el XLSX oficial de Content / post performance de LinkedIn. Se normaliza y vincula con content_id cuando es posible.</p><input type="file" name="file" accept=".xlsx" required className="mt-4 block w-full rounded-lg border border-slate-300 bg-white p-2 text-xs text-slate-500"/><button className={`mt-3 ${adminButtonPrimary}`}>Importar XLSX</button><p className="mt-4 text-[11px] leading-5 text-slate-500">Último import: {imports.find((row)=>row.account_type===account)?.imported_at||'ninguno'} · {imports.find((row)=>row.account_type===account)?.rows_imported||0} filas</p></form><div className={`${adminPanel} p-5`}><p className="text-sm font-semibold text-slate-950">Señales de negocio</p><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4"><div className="rounded-xl bg-slate-50 p-3"><p className="text-2xl font-semibold">{profileViews}</p><p className="text-xs text-slate-500">profile views</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-2xl font-semibold">{ratio(clicks,reach||impressions)}</p><p className="text-xs text-slate-500">click rate</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-2xl font-semibold">{ratio(saves,reach||impressions)}</p><p className="text-xs text-slate-500">save rate</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-2xl font-semibold">{ratio(followers,reach||impressions)}</p><p className="text-xs text-slate-500">follower conv.</p></div></div></div></div>

    <section className="mt-12"><SectionHeading eyebrow="Content attribution" title="Posts vinculados" count={latest.length}/>{latest.length===0?<EmptyState>No hay métricas LinkedIn importadas en el baseline actual.</EmptyState>:<div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-4 py-3">Post</th><th className="px-4 py-3">Imp.</th><th className="px-4 py-3">Reach</th><th className="px-4 py-3">React.</th><th className="px-4 py-3">Comments</th><th className="px-4 py-3">Saves</th><th className="px-4 py-3">Clicks</th><th className="px-4 py-3">Followers</th></tr></thead><tbody>{latest.sort((a,b)=>Number(b.impressions)-Number(a.impressions)).map((row)=>{const item=row.content_id?contentById.get(row.content_id):undefined;return <tr key={row.metric_id} className="border-t border-slate-200"><td className="max-w-sm px-4 py-3"><p className="line-clamp-2 font-medium text-slate-800">{item?.title||row.external_post_id||'Post no vinculado'}</p></td><td className="px-4 py-3">{Number(row.impressions).toLocaleString('es-ES')}</td><td className="px-4 py-3">{Number(row.reach).toLocaleString('es-ES')}</td><td className="px-4 py-3">{row.reactions}</td><td className="px-4 py-3">{row.comments}</td><td className="px-4 py-3">{row.saves}</td><td className="px-4 py-3">{row.clicks}</td><td className="px-4 py-3">{row.followers_gained}</td></tr>})}</tbody></table></div>}</section>

    <section id="website" className="mt-14"><SectionHeading eyebrow="Website · GA4 · G-3E1DK7935G" title="Website funnel" description="Los KPIs superiores proceden del total exacto del periodo de GA4. El desglose de adquisición se guarda aparte por fecha, source/medium, campaña y UTM content para no duplicar usuarios ni sesiones al agregar dimensiones."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><StatCard label="Sessions" value={periodTotal?webTotals.sessions:'—'}/><StatCard label="Engaged" value={periodTotal?webTotals.engaged:'—'}/><StatCard label="Page views" value={periodTotal?webTotals.views:'—'}/><StatCard label="Key events" value={periodTotal?webTotals.events:'—'} tone="blue"/><StatCard label="Discovery" value={periodTotal?webTotals.discovery:'—'} tone="violet"/><StatCard label="Bookings" value={periodTotal?webTotals.bookings:'—'} tone="green"/></div><div className={`mt-6 ${adminPanel} p-5`}><p className="text-sm font-semibold text-slate-950">Canales de adquisición</p>{topSources.length===0?<p className="mt-3 text-xs text-slate-500">Sin desglose GA4 sincronizado con el esquema actual. Ejecuta “Sincronizar Google”.</p>:<div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-xs"><thead className="text-slate-500"><tr><th className="py-2">Source / medium</th><th className="py-2">Sesiones</th><th className="py-2">Engaged</th><th className="py-2">Views</th></tr></thead><tbody>{topSources.map(([source,stats])=><tr key={source} className="border-t border-slate-100"><td className="py-2 font-medium text-slate-800">{source}</td><td>{stats.sessions}</td><td>{stats.engaged}</td><td>{stats.views}</td></tr>)}</tbody></table></div>}</div></section>

    <section id="seo" className="mt-14"><SectionHeading eyebrow="Organic acquisition" title="Google Search Console" description="Queries, clicks, impresiones, CTR y posición viven ya en el CRM cuando Google está autorizado."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Clicks" value={Number(integrated.seo.clicks).toLocaleString('es-ES')} tone="green"/><StatCard label="Impressions" value={Number(integrated.seo.impressions).toLocaleString('es-ES')} tone="blue"/><StatCard label="CTR" value={`${(Number(integrated.seo.ctr)*100).toFixed(2)}%`} tone="violet"/><StatCard label="Posición" value={Number(integrated.seo.position).toFixed(1)} tone="amber"/></div>{topQueries.length===0?<div className="mt-6"><EmptyState>Sin datos Search Console sincronizados. {integrated.sources.google_connected?'Pulsa “Sincronizar Google”.':'Autoriza Google una vez para activar GA4 y Search Console.'}</EmptyState></div>:<div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-4 py-3">Query</th><th className="px-4 py-3">Clicks</th><th className="px-4 py-3">Impresiones</th><th className="px-4 py-3">CTR</th><th className="px-4 py-3">Posición</th></tr></thead><tbody>{topQueries.map(([query,stats])=><tr key={query} className="border-t border-slate-200"><td className="max-w-lg px-4 py-3 font-medium text-slate-800">{query}</td><td className="px-4 py-3">{stats.clicks}</td><td className="px-4 py-3">{stats.impressions}</td><td className="px-4 py-3">{ratio(stats.clicks,stats.impressions)}</td><td className="px-4 py-3">{stats.impressions? (stats.positionWeighted/stats.impressions).toFixed(1):'—'}</td></tr>)}</tbody></table></div>}</section>

    <section id="business" className="mt-14 pb-12"><SectionHeading eyebrow="Cross-module" title="Resultado comercial y financiero" description="Esta sección demuestra la relación transversal: no se importa manualmente; lee directamente oportunidades y finanzas."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><StatCard label="Oportunidades" value={Number(integrated.commercial.opportunities)}/><StatCard label="Reuniones" value={Number(integrated.commercial.meetings)}/><StatCard label="Pipeline" value={euro(integrated.commercial.open_pipeline)} tone="blue"/><StatCard label="Facturado" value={euro(integrated.finance.invoiced)} tone="green"/><StatCard label="Cobrado" value={euro(integrated.finance.collected)} tone="green"/><StatCard label="Gasto" value={euro(integrated.finance.spent)} tone="amber"/></div>{!integrated.sources.google_connected&&oauth.configured&&<div className="mt-6"><a href="/api/growth-admin/google/connect?account=corporate&return_to=/growth-admin/analytics" className={adminButtonPrimary}>Autorizar Google para completar métricas</a></div>}</section>
  </AdminShell>
}