import { redirect } from 'next/navigation'
import AdminShell from '@/components/growth-admin/AdminShell'
import FinanceNav from '@/components/growth-admin/FinanceNav'
import { Badge, EmptyState, PageHeader, SectionHeading, StatCard, adminButtonSecondary, adminPanel } from '@/components/growth-admin/AdminUi'
import { isGrowthAdminAuthenticated, queryGrowthTable } from '@/lib/growth-admin'
import { getFinanceBundle } from '@/lib/growth-admin-performance'

export const dynamic='force-dynamic'
const n=(value:unknown)=>Number(value||0)
const euro=(value:unknown)=>`${n(value).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})} €`
type JournalLine={journal_line_id:string;journal_entry_id:string;account_code:string;description?:string;debit:number|string;credit:number|string;currency:string}

export default async function AccountingPage(){
  if(!(await isGrowthAdminAuthenticated())) redirect('/growth-admin/login')
  const [bundle,lines]=await Promise.all([
    getFinanceBundle(),
    queryGrowthTable<JournalLine>('finance_journal_lines',{tenant_id:'eq.sc-analytics',order:'created_at.desc',limit:'600'},{cacheSeconds:0}),
  ])
  const linesByEntry=new Map<string,JournalLine[]>()
  for(const line of lines){const list=linesByEntry.get(line.journal_entry_id)||[];list.push(line);linesByEntry.set(line.journal_entry_id,list)}
  const accountByCode=new Map(bundle.accounts.map((a)=>[String(a.account_code),a]))
  const confirmedInvoices=bundle.invoices.filter(row=>['reviewed','confirmed'].includes(String(row.review_status||''))&&!['void','cancelled'].includes(String(row.status||'')))
  const confirmedExpenses=bundle.expenses.filter(row=>['reviewed','confirmed'].includes(String(row.review_status||''))&&!['void','cancelled'].includes(String(row.status||'')))
  const confirmedPayments=bundle.payments.filter(row=>['reviewed','confirmed'].includes(String(row.review_status||'')))
  const hasConfirmedData=confirmedInvoices.length+confirmedExpenses.length+confirmedPayments.length>0
  const vatPosition=n(bundle.vat_output)-n(bundle.vat_input)
  const operatingResult=n(bundle.invoiced)-n(bundle.spent)
  const metric=(value:unknown)=>hasConfirmedData?euro(value):'—'
  return <AdminShell active="finance">
    <PageHeader eyebrow="Finanzas · Accounting" title="Contabilidad e impuestos" description="Capa contable de doble partida, posición fiscal estimada y auditoría. Un guion largo (—) significa que todavía no hay base confirmada suficiente; no se interpreta como 0 €." actions={<a href="/growth-admin/finance/reports" className="rounded-lg border border-white/20 bg-white/10 px-4 py-2.5 text-sm font-semibold text-white">Ver periodos →</a>}/>
    <FinanceNav active="/growth-admin/finance/accounting"/>

    {!hasConfirmedData&&<div className="mb-6 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900"><strong>Sin base contable confirmada suficiente.</strong><p className="mt-1">Puedes tener facturas, gastos, candidatos Gmail o movimientos bancarios en el sistema, pero hasta revisarlos/conciliarlos no entran en la posición estimada. Esto evita mostrar ceros falsos.</p><div className="mt-3 flex flex-wrap gap-2"><a href="/growth-admin/finance/invoices" className={adminButtonSecondary}>Revisar facturas</a><a href="/growth-admin/finance/expenses" className={adminButtonSecondary}>Revisar gastos</a><a href="/growth-admin/finance/cash" className={adminButtonSecondary}>Conciliar banco</a></div></div>}

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Ingresos confirmados" value={metric(bundle.invoiced)} tone="blue" note={`${confirmedInvoices.length} facturas confirmadas`}/><StatCard label="Gastos confirmados" value={metric(bundle.spent)} tone="violet" note={`${confirmedExpenses.length} gastos confirmados`}/><StatCard label="Resultado operativo" value={metric(operatingResult)} tone={hasConfirmedData&&operatingResult<0?'amber':'green'}/><StatCard label="IVA neto estimado" value={metric(vatPosition)} tone="amber" note={hasConfirmedData?`${euro(bundle.vat_output)} repercutido · ${euro(bundle.vat_input)} soportado`:'Esperando documentos confirmados'}/></div>

    <section className="mt-12"><SectionHeading eyebrow="Cómo funciona" title="Qué es un asiento contable" description="Un asiento es el registro equilibrado Debe/Haber de un hecho económico. El CRM lo crea a partir de documentos confirmados y conserva el vínculo al origen para evitar duplicarlo."/><div className="grid gap-4 md:grid-cols-3"><div className={`${adminPanel} p-5`}><p className="font-semibold text-slate-900">Factura confirmada</p><p className="mt-2 text-xs leading-5 text-slate-500">Genera la representación de ingreso, cliente/deudor, IVA y retención cuando corresponda.</p></div><div className={`${adminPanel} p-5`}><p className="font-semibold text-slate-900">Gasto confirmado</p><p className="mt-2 text-xs leading-5 text-slate-500">Representa gasto/proveedor, IVA soportado y otras partidas según la clasificación guardada.</p></div><div className={`${adminPanel} p-5`}><p className="font-semibold text-slate-900">Cobro / pago conciliado</p><p className="mt-2 text-xs leading-5 text-slate-500">Cierra o reduce saldos pendientes y mueve caja/banco. Un extracto sin conciliar no se convierte por sí solo en asiento definitivo.</p></div></div></section>

    <section className="mt-12"><SectionHeading eyebrow="Fiscalidad" title="Posición estimada" description="Solo usa documentos confirmados. No sustituye una liquidación tributaria ni valida la deducibilidad fiscal."/><div className="grid gap-4 md:grid-cols-3"><div className={`${adminPanel} p-5`}><p className="text-xs uppercase tracking-wider text-slate-400">IVA repercutido</p><p className="mt-2 text-2xl font-semibold">{metric(bundle.vat_output)}</p></div><div className={`${adminPanel} p-5`}><p className="text-xs uppercase tracking-wider text-slate-400">IVA soportado</p><p className="mt-2 text-2xl font-semibold">{metric(bundle.vat_input)}</p></div><div className={`${adminPanel} p-5`}><p className="text-xs uppercase tracking-wider text-slate-400">Retenciones facturas</p><p className="mt-2 text-2xl font-semibold">{metric(bundle.withholding_total)}</p></div></div></section>

    <section className="mt-14"><SectionHeading eyebrow="Plan contable" title="Cuentas" count={bundle.accounts.length}/>{bundle.accounts.length===0?<EmptyState>El plan contable no está inicializado. Esto es configuración, no un 0 financiero.</EmptyState>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{bundle.accounts.map((account)=><div key={String(account.account_code)} className={`${adminPanel} p-4`}><div className="flex items-center justify-between gap-3"><p className="font-mono text-sm font-semibold text-slate-950">{String(account.account_code)}</p><Badge>{String(account.account_type)}</Badge></div><p className="mt-2 text-sm text-slate-700">{String(account.name)}</p><p className="mt-1 text-[11px] text-slate-400">Saldo natural: {String(account.normal_balance)}</p></div>)}</div>}</section>

    <section className="mt-14"><SectionHeading eyebrow="Libro diario" title="Asientos automáticos" description="Cada asiento conserva source_type/source_id. El mismo documento no debe contabilizarse dos veces." count={bundle.journal_entries.length}/>{bundle.journal_entries.length===0?<EmptyState>No hay asientos confirmados. Los históricos importados no se postean retroactivamente sin revisión.</EmptyState>:<div className="space-y-4">{bundle.journal_entries.map((entry)=>{const entryLines=linesByEntry.get(String(entry.journal_entry_id))||[];return <div key={String(entry.journal_entry_id)} className={`${adminPanel} overflow-hidden`}><div className="flex flex-col gap-2 bg-slate-50 px-5 py-4 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-semibold text-slate-950">{String(entry.description)}</p><p className="text-xs text-slate-500">{String(entry.entry_date)} · {String(entry.source_type)} · {String(entry.source_id||'')}</p></div><Badge tone="green">{String(entry.status)}</Badge></div><div className="overflow-x-auto"><table className="min-w-full text-left text-xs"><thead><tr className="text-slate-400"><th className="px-5 py-2">Cuenta</th><th className="px-5 py-2">Debe</th><th className="px-5 py-2">Haber</th></tr></thead><tbody>{entryLines.map((line)=><tr key={line.journal_line_id} className="border-t border-slate-100"><td className="px-5 py-2.5">{line.account_code} · {String(accountByCode.get(line.account_code)?.name||'')}</td><td className="px-5 py-2.5">{n(line.debit)?euro(line.debit):'—'}</td><td className="px-5 py-2.5">{n(line.credit)?euro(line.credit):'—'}</td></tr>)}</tbody></table></div></div>})}</div>}</section>

    <section className="mt-14 pb-12"><SectionHeading eyebrow="Audit trail" title="Trazabilidad financiera" description="Emisión, revisión, conciliación y cambios relevantes dejan rastro." count={bundle.audit_events.length}/>{bundle.audit_events.length===0?<EmptyState>Sin eventos de auditoría todavía.</EmptyState>:<div className="space-y-2">{bundle.audit_events.slice(0,50).map((event)=><div key={String(event.audit_event_id)} className={`${adminPanel} flex flex-col gap-2 p-4 md:flex-row md:items-center md:justify-between`}><div><p className="text-sm font-semibold text-slate-900">{String(event.action)}</p><p className="text-xs text-slate-500">{String(event.entity_type)} · {String(event.entity_id)}</p></div><p className="text-xs text-slate-400">{new Date(String(event.occurred_at)).toLocaleString('es-ES')}</p></div>)}</div>}</section>
  </AdminShell>
}
