import { redirect } from 'next/navigation'
import AdminShell from '@/components/growth-admin/AdminShell'
import FinanceNav from '@/components/growth-admin/FinanceNav'
import { Badge, EmptyState, PageHeader, SectionHeading, adminButtonPrimary, adminButtonSecondary, adminInput, adminPanel, statusTone } from '@/components/growth-admin/AdminUi'
import { isGrowthAdminAuthenticated } from '@/lib/growth-admin'
import { getFinanceBundle } from '@/lib/growth-admin-performance'

export const dynamic='force-dynamic'
const n=(value:unknown)=>Number(value||0)
const money=(value:unknown,currency='EUR')=>`${n(value).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})} ${currency}`
type Params={gmail_candidates?:string;gmail_messages?:string;gmail_errors?:string}

export default async function ExpensesPage({searchParams}:{searchParams:Promise<Params>}){
  if(!(await isGrowthAdminAuthenticated())) redirect('/growth-admin/login')
  const params=await searchParams
  const bundle=await getFinanceBundle()
  const vendors=bundle.counterparties.filter((c)=>c.kind==='vendor'||c.kind==='both')
  const candidates=bundle.import_candidates
  return <AdminShell active="finance">
    <PageHeader eyebrow="Finanzas · Accounts payable" title="Gastos" description="Registro manual y bandeja de facturas/recibos detectados desde Gmail. La automatización propone; tú confirmas antes de contabilizar." actions={<form action="/api/growth-admin/finance/gmail-scan" method="post"><input type="hidden" name="days" value="14"/><button className="rounded-lg border border-white/20 bg-white/10 px-4 py-2.5 text-sm font-semibold text-white hover:bg-white/15">Actualizar Gmail ahora</button></form>}/>
    <FinanceNav active="/growth-admin/finance/expenses"/>
    {params.gmail_messages!==undefined&&<div className={`mb-6 rounded-2xl border p-4 text-sm ${Number(params.gmail_errors||0)>0?'border-amber-200 bg-amber-50 text-amber-900':'border-emerald-200 bg-emerald-50 text-emerald-800'}`}><strong>Sincronización Gmail completada.</strong> Se revisaron {params.gmail_messages} mensajes y se procesaron {params.gmail_candidates||0} candidatos.{Number(params.gmail_errors||0)>0&&` Hubo ${params.gmail_errors} errores parciales; revisa Integraciones si faltan permisos o una cuenta expiró.`}</div>}

    <section><SectionHeading eyebrow="Entrada manual" title="Registrar gasto" description="Úsalo para gastos sin correo, tickets o correcciones controladas."/><form action="/api/growth-admin/finance" method="post" className={`${adminPanel} grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-4`}>
      <input type="hidden" name="type" value="expense"/><input type="hidden" name="return_to" value="/growth-admin/finance/expenses"/>
      <select name="counterparty_id" className={adminInput}><option value="">Proveedor opcional</option>{vendors.map((v)=><option key={v.counterparty_id} value={v.counterparty_id}>{v.legal_name}</option>)}</select>
      <input required name="vendor" placeholder="Proveedor" className={adminInput}/><input name="vendor_tax_id" placeholder="NIF / VAT proveedor" className={adminInput}/><input name="invoice_number" placeholder="Nº factura / recibo" className={adminInput}/>
      <input required type="date" name="expense_date" className={adminInput}/><input name="category" placeholder="Categoría" className={adminInput}/><select name="currency" className={adminInput}><option>EUR</option><option>USD</option></select><input type="number" step="0.000001" name="fx_rate" placeholder="Cambio a EUR si USD" className={adminInput}/>
      <input required type="number" min="0" step="0.01" name="subtotal" placeholder="Base" className={adminInput}/><input type="number" min="0" step="0.01" name="vat_rate" placeholder="IVA %" className={adminInput}/><input type="number" min="0" step="0.01" name="withholding_rate" placeholder="Retención %" className={adminInput}/><input type="number" min="0" step="0.01" name="total" placeholder="Total opcional" className={adminInput}/>
      <textarea name="notes" placeholder="Notas" className={`${adminInput} min-h-20 md:col-span-2 xl:col-span-4`}/><div className="xl:col-span-4"><button className={adminButtonPrimary}>Registrar gasto pendiente de revisión</button></div>
    </form></section>

    <section className="mt-14"><SectionHeading eyebrow="Gmail · Human in the loop" title="Gastos detectados" description="Estos correos todavía NO forman parte de la contabilidad. Revisa proveedor, importe y justificante antes de confirmar." count={candidates.length}/>
      {candidates.length===0?<EmptyState>No hay candidatos Gmail pendientes. Si acabas de sincronizar y el contador fue 0, significa que no se detectaron nuevos candidatos en esa ventana; si nunca has conectado Gmail, ve a Integraciones.</EmptyState>:<div className="grid gap-4 xl:grid-cols-2">{candidates.map((candidate)=>{const d=(candidate.extracted_data||{}) as Record<string,unknown>; const attachments=Array.isArray(d.attachment_files)?d.attachment_files as Array<Record<string,unknown>>:[]; return <div key={candidate.candidate_id} className={`${adminPanel} p-5`}><div className="flex items-start justify-between gap-4"><div><p className="font-semibold text-slate-950">{String(d.vendor||'Proveedor sin identificar')}</p><p className="mt-1 text-xs text-slate-500">{String(d.expense_date||'Sin fecha')} · {String(d.invoice_number||'Sin nº factura')} · {candidate.source_account||'Gmail'}</p></div><Badge tone={Number(candidate.confidence||0)>=.8?'green':'amber'}>{Math.round(Number(candidate.confidence||0)*100)}% confianza</Badge></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-400">Total</span><p className="mt-1 font-semibold text-slate-900">{money(d.total,d.currency?String(d.currency):'EUR')}</p></div><div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-400">Categoría</span><p className="mt-1 font-semibold text-slate-900">{String(d.category||'Pendiente')}</p></div></div>{d.subject&&<p className="mt-3 text-xs leading-5 text-slate-500">{String(d.subject)}</p>}<div className="mt-4 flex flex-wrap gap-2">{attachments.map((file,index)=><a key={String(file.id||index)} target="_blank" rel="noreferrer" href={String(file.url||`https://drive.google.com/file/d/${file.id}/view`)} className={adminButtonSecondary}>{String(file.name||'Adjunto')} ↗</a>)}<form action="/api/growth-admin/finance/import-candidate" method="post"><input type="hidden" name="candidate_id" value={String(candidate.candidate_id)}/><input type="hidden" name="action" value="confirm"/><input type="hidden" name="return_to" value="/growth-admin/finance/expenses"/><button className={adminButtonPrimary}>Confirmar gasto</button></form><form action="/api/growth-admin/finance/import-candidate" method="post"><input type="hidden" name="candidate_id" value={String(candidate.candidate_id)}/><input type="hidden" name="action" value="discard"/><input type="hidden" name="return_to" value="/growth-admin/finance/expenses"/><button className={adminButtonSecondary}>Descartar</button></form></div></div>})}</div>}
    </section>

    <section className="mt-14 pb-12"><SectionHeading eyebrow="Libro operativo" title="Gastos registrados" count={bundle.expenses.length}/>{bundle.expenses.length===0?<EmptyState>No hay gastos confirmados o registrados todavía.</EmptyState>:<div className="space-y-3">{bundle.expenses.map((expense)=>{const reviewed=['reviewed','confirmed'].includes(String(expense.review_status||'')); return <div key={expense.expense_id} className={`${adminPanel} flex flex-col gap-4 p-4 md:flex-row md:items-center md:justify-between`}><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-slate-950">{expense.vendor||expense.category||'Gasto'}</p><Badge tone={statusTone(String(expense.status||''))}>{String(expense.status||'recorded')}</Badge><Badge tone={reviewed?'green':'amber'}>{String(expense.review_status||'pending_review')}</Badge></div><p className="mt-1 text-xs text-slate-500">{expense.expense_date||'—'} · {expense.category||'Sin categoría'} · {expense.invoice_number||'Sin nº factura'}</p></div><div className="flex items-center gap-3"><span className="font-semibold text-slate-950">{money(expense.total,expense.currency||'EUR')}</span>{!reviewed&&<form action="/api/growth-admin/finance" method="post"><input type="hidden" name="type" value="review"/><input type="hidden" name="entity" value="expense"/><input type="hidden" name="entity_id" value={String(expense.expense_id)}/><input type="hidden" name="decision" value="reviewed"/><input type="hidden" name="return_to" value="/growth-admin/finance/expenses"/><button className={adminButtonSecondary}>✓ Doble check</button></form>}{expense.receipt_url&&<a href={String(expense.receipt_url)} target="_blank" rel="noreferrer" className={adminButtonSecondary}>Justificante ↗</a>}</div></div>})}</div>}
    </section>
  </AdminShell>
}
