import { redirect } from 'next/navigation'
import AdminShell from '@/components/growth-admin/AdminShell'
import { Badge, EmptyState, PageHeader, SectionHeading, StatCard, adminButtonPrimary, adminInput, adminPanel } from '@/components/growth-admin/AdminUi'
import { isGrowthAdminAuthenticated } from '@/lib/growth-admin'
import { getDealDeskBundle } from '@/lib/growth-admin-performance'

export const dynamic='force-dynamic'

type Params={opportunity?:string;step?:string;saved?:string;created?:string}
const value=(obj:Record<string,any>|undefined,key:string)=>String(obj?.[key]??'')
const num=(obj:Record<string,any>|undefined,key:string,fallback='')=>String(obj?.[key]??fallback)
const money=(v:unknown,currency='EUR')=>new Intl.NumberFormat('es-ES',{style:'currency',currency:currency||'EUR',maximumFractionDigits:0}).format(Number(v||0))

function StepLink({href,label,active}:{href:string;label:string;active:boolean}){return <a href={href} className={`rounded-full border px-4 py-2 text-xs font-semibold ${active?'border-indigo-300 bg-indigo-50 text-indigo-800':'border-slate-200 bg-white text-slate-600 hover:border-slate-300'}`}>{label}</a>}
function ScoreInput({name,label,defaultValue}:{name:string;label:string;defaultValue:string}){return <label className="text-xs font-semibold text-slate-600">{label}<select name={name} defaultValue={defaultValue||'0'} className={`mt-2 w-full ${adminInput}`}><option value="0">Sin valorar</option><option value="1">1 · Bajo</option><option value="2">2</option><option value="3">3 · Medio</option><option value="4">4</option><option value="5">5 · Alto</option></select></label>}

export default async function DealDeskPage({searchParams}:{searchParams:Promise<Params>}){
  if(!(await isGrowthAdminAuthenticated())) redirect('/growth-admin/login')
  const params=await searchParams
  const bundle=await getDealDeskBundle()
  const selectedId=params.opportunity||bundle.opportunities[0]?.opportunity_id||''
  const opportunity=bundle.opportunities.find((item)=>item.opportunity_id===selectedId)
  const workspace=bundle.workspaces.find((item)=>String(item.opportunity_id)===selectedId) as Record<string,any>|undefined
  const step=['qualification','discovery','proposal','budget'].includes(params.step||'')?String(params.step):String(workspace?.status||'qualification')
  const q=(workspace?.qualification||{}) as Record<string,any>
  const d=(workspace?.discovery||{}) as Record<string,any>
  const p=(workspace?.proposal||{}) as Record<string,any>
  const b=(workspace?.budget||{}) as Record<string,any>
  const peopleForCompany=opportunity?bundle.people.filter((person)=>String(person.company_id)===String(opportunity.company_id)):bundle.people

  return <AdminShell active="commercial">
    <PageHeader eyebrow="Comercial · Conversión" title="Deal Desk" description="Qualification, discovery, propuesta y presupuesto son ahora un único expediente conectado a la oportunidad. Lo que guardas aquí actualiza pipeline, valor y siguiente acción del CRM." actions={<a href="/growth-admin/commercial" className="rounded-lg border border-white/20 bg-white/10 px-4 py-2.5 text-sm font-semibold text-white">← Comercial</a>}/>
    {params.saved&&<div className="mb-6 rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm text-emerald-800">Guardado: {params.saved}. La oportunidad y el Deal Desk ya comparten el mismo estado.</div>}

    {bundle.companies.length>0&&<section className={`${adminPanel} mb-8 p-5`}><p className="text-sm font-semibold text-slate-950">Crear expediente desde un lead</p><p className="mt-1 text-xs text-slate-500">Convierte una empresa ya investigada en oportunidad y empieza la qualification sin duplicar datos.</p><form action="/api/growth-admin/deal-desk" method="post" className="mt-4 grid gap-3 md:grid-cols-[1.2fr_1.2fr_1fr_auto] md:items-end"><input type="hidden" name="action" value="create"/><label className="text-xs font-semibold text-slate-600">Empresa<select name="company_id" required className={`mt-2 w-full ${adminInput}`}><option value="">Selecciona empresa</option>{bundle.companies.map((company)=><option key={String(company.company_id)} value={String(company.company_id)}>{String(company.name)}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Contacto principal<select name="primary_person_id" className={`mt-2 w-full ${adminInput}`}><option value="">Sin contacto todavía</option>{bundle.people.map((person)=><option key={String(person.person_id)} value={String(person.person_id)}>{String(person.name)} · {String(person.role||'')}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Divisa<select name="currency" defaultValue="EUR" className={`mt-2 w-full ${adminInput}`}><option>EUR</option><option>USD</option></select></label><button className={adminButtonPrimary}>Crear expediente</button></form></section>}

    {bundle.opportunities.length===0?<EmptyState>No hay oportunidades activas en el baseline actual. Cuando un lead pase a discovery —o crees un expediente desde una empresa— aparecerá aquí y podrás trabajar qualification, discovery, propuesta y presupuesto sobre el mismo registro.</EmptyState>:<>
      <section className={`${adminPanel} p-5`}><div className="grid gap-4 xl:grid-cols-[1.4fr_1fr]"><div><label className="text-xs font-semibold text-slate-600">Oportunidad<select className={`mt-2 w-full ${adminInput}`} defaultValue={selectedId} onChange={undefined}>{bundle.opportunities.map((item)=><option key={item.opportunity_id} value={item.opportunity_id}>{item.company_name||item.name} · {item.stage}</option>)}</select></label><div className="mt-3 flex flex-wrap gap-2">{bundle.opportunities.map((item)=><a key={item.opportunity_id} href={`/growth-admin/deal-desk?opportunity=${encodeURIComponent(item.opportunity_id)}&step=${step}`} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${item.opportunity_id===selectedId?'border-indigo-200 bg-indigo-50 text-indigo-700':'border-slate-200 bg-white text-slate-500'}`}>{item.company_name||item.name}</a>)}</div></div>{opportunity&&<div className="grid grid-cols-3 gap-3"><StatCard label="Etapa" value={opportunity.stage||'—'}/><StatCard label="Prob." value={`${Number(opportunity.probability||0)}%`} tone="blue"/><StatCard label="Valor" value={money(opportunity.value,opportunity.currency)} tone="green"/></div>}</div></section>

      {opportunity&&<>
        <section className="mt-8"><div className="flex flex-wrap gap-2"><StepLink href={`/growth-admin/deal-desk?opportunity=${selectedId}&step=qualification`} label="1 · Qualification" active={step==='qualification'}/><StepLink href={`/growth-admin/deal-desk?opportunity=${selectedId}&step=discovery`} label="2 · Discovery" active={step==='discovery'}/><StepLink href={`/growth-admin/deal-desk?opportunity=${selectedId}&step=proposal`} label="3 · Proposal Builder" active={step==='proposal'}/><StepLink href={`/growth-admin/deal-desk?opportunity=${selectedId}&step=budget`} label="4 · Budget Helper" active={step==='budget'}/></div></section>

        <section className="mt-8 grid gap-5 xl:grid-cols-[1.35fr_0.65fr]">
          <div>
            {step==='qualification'&&<><SectionHeading eyebrow="Paso 1" title="Qualification" description="Valora el encaje comercial con criterios explícitos. El score actualiza automáticamente la probabilidad de la oportunidad."/><form action="/api/growth-admin/deal-desk" method="post" className={`${adminPanel} grid gap-4 p-6 md:grid-cols-2`}><input type="hidden" name="action" value="qualification"/><input type="hidden" name="opportunity_id" value={selectedId}/><input type="hidden" name="return_to" value="/growth-admin/deal-desk"/><label className="md:col-span-2 text-xs font-semibold text-slate-600">Problema / oportunidad<textarea name="problem" defaultValue={value(q,'problem')} className={`mt-2 min-h-24 w-full ${adminInput}`}/></label><label className="md:col-span-2 text-xs font-semibold text-slate-600">Impacto de negocio<textarea name="impact" defaultValue={value(q,'impact')} className={`mt-2 min-h-20 w-full ${adminInput}`}/></label><label className="text-xs font-semibold text-slate-600">Decisor<input name="decision_maker" defaultValue={value(q,'decision_maker')||opportunity.person_name||''} className={`mt-2 w-full ${adminInput}`}/></label><label className="text-xs font-semibold text-slate-600">Presupuesto conocido<input name="budget_range" defaultValue={value(q,'budget_range')} placeholder="Ej. 5k–10k EUR" className={`mt-2 w-full ${adminInput}`}/></label><label className="md:col-span-2 text-xs font-semibold text-slate-600">Datos / sistemas disponibles<textarea name="data_readiness" defaultValue={value(q,'data_readiness')} className={`mt-2 min-h-20 w-full ${adminInput}`}/></label><div className="md:col-span-2 grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><ScoreInput name="problem_score" label="Problema definido" defaultValue={num(q,'problem_score','0')}/><ScoreInput name="impact_score" label="Impacto" defaultValue={num(q,'impact_score','0')}/><ScoreInput name="urgency_score" label="Urgencia" defaultValue={num(q,'urgency_score','0')}/><ScoreInput name="authority_score" label="Acceso a decisor" defaultValue={num(q,'authority_score','0')}/><ScoreInput name="budget_score" label="Presupuesto" defaultValue={num(q,'budget_score','0')}/><ScoreInput name="data_score" label="Datos / viabilidad" defaultValue={num(q,'data_score','0')}/></div><label className="md:col-span-2 text-xs font-semibold text-slate-600">Notas<textarea name="qualification_notes" defaultValue={value(q,'qualification_notes')} className={`mt-2 min-h-20 w-full ${adminInput}`}/></label><div className="md:col-span-2"><button className={adminButtonPrimary}>Guardar qualification</button></div></form></>}

            {step==='discovery'&&<><SectionHeading eyebrow="Paso 2" title="Discovery Call" description="Documento vivo para preparar y registrar la llamada. El siguiente paso se sincroniza con la oportunidad."/><form action="/api/growth-admin/deal-desk" method="post" className={`${adminPanel} grid gap-4 p-6 md:grid-cols-2`}><input type="hidden" name="action" value="discovery"/><input type="hidden" name="opportunity_id" value={selectedId}/><input type="hidden" name="return_to" value="/growth-admin/deal-desk"/>{[['current_process','Proceso actual'],['desired_state','Estado deseado'],['business_value','Valor de negocio'],['systems_data','Sistemas y datos'],['constraints','Restricciones'],['budget_timing','Presupuesto y timing'],['decision_process','Proceso de decisión'],['discovery_notes','Notas / conclusiones']].map(([name,label])=><label key={name} className="text-xs font-semibold text-slate-600">{label}<textarea name={name} defaultValue={value(d,name)} className={`mt-2 min-h-24 w-full ${adminInput}`}/></label>)}<label className="text-xs font-semibold text-slate-600">Siguiente acción<input name="next_action" defaultValue={value(d,'next_action')} className={`mt-2 w-full ${adminInput}`}/></label><label className="text-xs font-semibold text-slate-600">Fecha siguiente acción<input type="datetime-local" name="next_action_at" defaultValue={value(d,'next_action_at').slice(0,16)} className={`mt-2 w-full ${adminInput}`}/></label><div className="md:col-span-2"><button className={adminButtonPrimary}>Guardar discovery</button></div></form></>}

            {step==='proposal'&&<><SectionHeading eyebrow="Paso 3" title="Proposal Builder" description="Estructura la propuesta sobre la evidencia ya guardada; no es una tarjeta decorativa. Scope y aceptación quedan ligados a la oportunidad."/><form action="/api/growth-admin/deal-desk" method="post" className={`${adminPanel} grid gap-4 p-6 md:grid-cols-2`}><input type="hidden" name="action" value="proposal"/><input type="hidden" name="opportunity_id" value={selectedId}/><input type="hidden" name="return_to" value="/growth-admin/deal-desk"/>{[['objective','Objetivo'],['scope','Alcance'],['deliverables','Entregables'],['exclusions','Fuera de alcance'],['timeline','Timing / fases'],['acceptance_criteria','Criterios de aceptación'],['assumptions','Supuestos y dependencias'],['proposal_notes','Notas comerciales']].map(([name,label])=><label key={name} className="text-xs font-semibold text-slate-600">{label}<textarea name={name} defaultValue={value(p,name)} className={`mt-2 min-h-24 w-full ${adminInput}`}/></label>)}<div className="md:col-span-2"><button className={adminButtonPrimary}>Guardar propuesta</button></div></form></>}

            {step==='budget'&&<><SectionHeading eyebrow="Paso 4" title="Budget Helper" description="Calcula el precio desde esfuerzo, costes, contingencia y margen. El precio final se escribe directamente en el valor de la oportunidad."/><form action="/api/growth-admin/deal-desk" method="post" className={`${adminPanel} grid gap-4 p-6 md:grid-cols-2 xl:grid-cols-3`}><input type="hidden" name="action" value="budget"/><input type="hidden" name="opportunity_id" value={selectedId}/><input type="hidden" name="return_to" value="/growth-admin/deal-desk"/><label className="text-xs font-semibold text-slate-600">Horas estimadas<input type="number" step="0.5" min="0" name="estimated_hours" defaultValue={num(b,'estimated_hours','')} className={`mt-2 w-full ${adminInput}`}/></label><label className="text-xs font-semibold text-slate-600">Coste interno / h<input type="number" step="0.01" min="0" name="internal_rate" defaultValue={num(b,'internal_rate','')} className={`mt-2 w-full ${adminInput}`}/></label><label className="text-xs font-semibold text-slate-600">Costes externos<input type="number" step="0.01" min="0" name="external_costs" defaultValue={num(b,'external_costs','0')} className={`mt-2 w-full ${adminInput}`}/></label><label className="text-xs font-semibold text-slate-600">Contingencia %<input type="number" step="1" min="0" name="contingency_pct" defaultValue={num(b,'contingency_pct','10')} className={`mt-2 w-full ${adminInput}`}/></label><label className="text-xs font-semibold text-slate-600">Margen objetivo %<input type="number" step="1" min="0" max="95" name="target_margin_pct" defaultValue={num(b,'target_margin_pct','35')} className={`mt-2 w-full ${adminInput}`}/></label><label className="text-xs font-semibold text-slate-600">Divisa<select name="currency" defaultValue={value(b,'currency')||opportunity.currency||'EUR'} className={`mt-2 w-full ${adminInput}`}><option>EUR</option><option>USD</option></select></label><label className="text-xs font-semibold text-slate-600 xl:col-span-2">Precio final<input type="number" step="0.01" min="0" name="final_price" defaultValue={num(b,'final_price','')} placeholder="Vacío = usar precio sugerido" className={`mt-2 w-full ${adminInput}`}/></label><label className="text-xs font-semibold text-slate-600 xl:col-span-3">Notas de pricing<textarea name="pricing_notes" defaultValue={value(b,'pricing_notes')} className={`mt-2 min-h-20 w-full ${adminInput}`}/></label><div className="xl:col-span-3 flex flex-wrap gap-3"><button className={adminButtonPrimary}>Calcular y guardar</button>{b.suggested_price!==undefined&&<span className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-sm font-semibold text-emerald-800">Sugerido actual: {money(b.suggested_price,value(b,'currency')||opportunity.currency)}</span>}</div></form></>}
          </div>

          <aside className="space-y-5"><div className={`${adminPanel} p-5`}><p className="text-xs font-semibold uppercase tracking-[0.16em] text-indigo-600">Contexto automático</p><h3 className="mt-3 text-xl font-semibold text-slate-950">{opportunity.company_name||opportunity.name}</h3><p className="mt-2 text-sm text-slate-600">{opportunity.person_name?`${opportunity.person_name} · ${opportunity.role||''}`:'Sin contacto principal'}</p><div className="mt-4 space-y-3 text-xs leading-5 text-slate-600"><div><span className="font-semibold text-slate-800">Oferta recomendada:</span><br/>{opportunity.recommended_offer||opportunity.recommended_service||'Pendiente'}</div><div><span className="font-semibold text-slate-800">Sector:</span><br/>{opportunity.industry||'—'} · {opportunity.country||'—'}</div>{opportunity.next_action_at&&<div><span className="font-semibold text-slate-800">Próxima acción:</span><br/>{new Date(opportunity.next_action_at).toLocaleString('es-ES')}</div>}</div></div><div className={`${adminPanel} p-5`}><p className="text-sm font-semibold text-slate-950">Mover etapa</p><form action="/api/growth-admin/deal-desk" method="post" className="mt-3 space-y-3"><input type="hidden" name="action" value="stage"/><input type="hidden" name="opportunity_id" value={selectedId}/><input type="hidden" name="return_to" value="/growth-admin/deal-desk"/><select name="stage" defaultValue={opportunity.stage} className={`w-full ${adminInput}`}><option value="qualification">Qualification</option><option value="discovery">Discovery</option><option value="discovery_booked">Discovery booked</option><option value="proposal">Proposal</option><option value="negotiation">Negotiation</option><option value="won">Won</option><option value="lost">Lost</option></select><button className={adminButtonPrimary}>Actualizar etapa</button></form></div>{peopleForCompany.length>0&&<div className={`${adminPanel} p-5`}><p className="text-sm font-semibold text-slate-950">Contactos vinculados</p><div className="mt-3 space-y-2">{peopleForCompany.slice(0,6).map((person)=><div key={String(person.person_id)} className="rounded-xl bg-slate-50 p-3 text-xs"><p className="font-semibold text-slate-800">{String(person.name)}</p><p className="mt-1 text-slate-500">{String(person.role||'')}</p></div>)}</div></div>}</aside>
        </section>
      </>}
    </>}
  </AdminShell>
}
