'use client'

import Link from 'next/link'
import { useSiteLanguage } from '@/components/SiteLanguageProvider'

const COPY={
 es:{eyebrow:'PARTNER ANALÍTICO EXTERNO',title:'Capacidad de Data, IA y matemáticas sin construir un departamento interno.',body:'Podemos resolver un proyecto puntual o convertirnos en la capa analítica que conoce tu negocio y vuelve a entrar cuando aparece una nueva decisión. El objetivo no es vender más tecnología: es conservar contexto, aprender del negocio y aportar la especialización adecuada cuando hace falta.',benefits:[['Continuidad','El conocimiento del negocio no se pierde entre proyectos.'],['Flexibilidad','Forecasting, optimización, ML, automatización, BI o ingeniería según el problema.'],['Menos estructura fija','Accedes a capacidad especialista sin tener que crear todos los roles internamente.'],['Responsabilidad','Una relación clara que conecta problema, solución, medición y mejora.']],button:'Qué implica ser partner analítico'},
 ca:{eyebrow:'PARTNER ANALÍTIC EXTERN',title:'Capacitat de dades, IA i matemàtiques sense construir un departament intern.',body:'Podem resoldre un projecte puntual o convertir-nos en la capa analítica que coneix el teu negoci i torna a entrar quan apareix una nova decisió. L’objectiu no és vendre més tecnologia: és conservar context, aprendre del negoci i aportar l’especialització adequada quan cal.',benefits:[['Continuïtat','El coneixement del negoci no es perd entre projectes.'],['Flexibilitat','Forecasting, optimització, ML, automatització, BI o enginyeria segons el problema.'],['Menys estructura fixa','Accedeixes a capacitat especialista sense haver de crear tots els rols internament.'],['Responsabilitat','Una relació clara que connecta problema, solució, mesura i millora.']],button:'Què implica ser partner analític'},
 en:{eyebrow:'EXTERNAL ANALYTICAL PARTNER',title:'Data, AI and mathematical capability without building a full internal department.',body:'We can solve one project or become the analytical layer that learns the business and returns when a new decision appears. The objective is not to sell more technology: it is to retain context, understand the operation and bring the right specialism when it is needed.',benefits:[['Continuity','Business context is retained instead of being restarted for every project.'],['Flexibility','Forecasting, optimisation, ML, automation, BI or engineering according to the problem.'],['Lower fixed structure','Access specialist capability without creating every role internally.'],['Accountability','One clear relationship connecting problem, solution, measurement and improvement.']],button:'What an analytical partnership means'},
 } as const

export default function AnalyticalPartnerSection(){
 const {lang}=useSiteLanguage(),t=COPY[lang]
 return <section className="border-y border-slate-200 bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-6 py-20"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-indigo-300">{t.eyebrow}</p><h2 className="mt-5 max-w-xl text-4xl leading-tight md:text-5xl" style={{fontFamily:'var(--font-playfair)'}}>{t.title}</h2><p className="mt-6 max-w-xl text-base leading-8 text-slate-300">{t.body}</p><Link href="/partner-analitico" className="mt-7 inline-flex rounded-lg bg-white px-5 py-3 text-sm font-semibold text-slate-950">{t.button}</Link></div><div className="divide-y divide-slate-800 border-y border-slate-800">{t.benefits.map(([title,body],i)=><div key={title} className="grid gap-3 py-5 sm:grid-cols-[60px_180px_1fr]"><span className="text-xs font-semibold text-indigo-300">0{i+1}</span><h3 className="font-semibold">{title}</h3><p className="text-sm leading-6 text-slate-400">{body}</p></div>)}</div></div></div></section>
}
