import { PUBLICATION_MODES, SC_BRAND, VISUAL_FORMATS, type PublicationMode, type VisualFormatKey } from '@/lib/brand-system'

export type VisualElementKind='text'|'metric'|'rect'|'line'|'logo'|'tag'
export type TextAlign='left'|'center'|'right'
export type VisualTemplateKey='insight_dark'|'insight_light'|'metric_focus'|'comparison_split'|'process_steps'|'case_result'|'article_editorial'|'image_only_statement'
export interface VisualElement{id:string;kind:VisualElementKind;role?:string;x:number;y:number;w:number;h:number;text?:string;value?:string;label?:string;fontSize?:number;fontFamily?:string;fontWeight?:number;color?:string;fill?:string;stroke?:string;strokeWidth?:number;radius?:number;align?:TextAlign;opacity?:number;src?:string;locked?:boolean;hidden?:boolean}
export interface VisualDesign{designId?:string;name:string;templateKey:VisualTemplateKey;formatKey:VisualFormatKey;publicationMode:PublicationMode;background:string;elements:VisualElement[];contentId?:string;assetPath?:string;status?:string}
export interface VisualStudioContentSeed{content_id:string;title:string;body?:string;channel:string;content_type:string;language?:string;content_family?:string;visual_type?:string;visual_path?:string;publication_mode?:PublicationMode;hashtags?:string[];visual_strategy?:Record<string,unknown>|null}
export interface VisualTemplateMeta{key:VisualTemplateKey;label:string;description:string;bestFor:string;families:readonly('linkedin'|'website'|'presentation'|'vertical')[]}
export const VISUAL_TEMPLATES:readonly VisualTemplateMeta[]=[
{key:'insight_dark',label:'Insight · Dark',description:'Tesis corta con jerarquía fuerte.',bestFor:'Opinión, educación y argumentos contrarios.',families:['linkedin','website','presentation']},
{key:'insight_light',label:'Insight · Light',description:'Composición editorial clara con logo oscuro.',bestFor:'Posts ejecutivos y portadas limpias.',families:['linkedin','website','presentation']},
{key:'metric_focus',label:'Métrica protagonista',description:'Un número dominante y contexto breve.',bestFor:'Métricas reales y señales cuantificadas.',families:['linkedin','website','presentation']},
{key:'comparison_split',label:'Comparación',description:'Dos marcos enfrentados sin saturar texto.',bestFor:'Trade-offs, antes/después y framing.',families:['linkedin','website','presentation']},
{key:'process_steps',label:'Proceso / framework',description:'Secuencia visual de 3–5 pasos.',bestFor:'Sistemas, decisiones y workflows.',families:['linkedin','website','presentation']},
{key:'case_result',label:'Caso / resultado',description:'Problema y resultado en una composición.',bestFor:'Casos y resultados prácticos.',families:['linkedin','website','presentation']},
{key:'article_editorial',label:'Article editorial',description:'Hero horizontal para Knowledge.',bestFor:'Artículos, Open Graph y portadas.',families:['website','presentation','linkedin']},
{key:'image_only_statement',label:'Statement',description:'Una frase corta hace de stop-scroll.',bestFor:'Tesis potente, pregunta o tensión defendible.',families:['linkedin','vertical','presentation']},
]
const brand=SC_BRAND
const fmt=(key:VisualFormatKey)=>VISUAL_FORMATS[key]
const safe=(w:number,h:number)=>Math.max(44,Math.round(Math.min(w,h)*.06))
const clean=(value:string)=>String(value||'').replace(/[→←↑↓↔↕⇒⇐⇑⇓↗↘↙↖➜➝➡⬅➤➔]/g,' ').replace(/\s+/g,' ').trim()
const clamp=(value:string,max=220)=>{const v=clean(value);return v.length<=max?v:`${v.slice(0,max-1).trim()}…`}
const firstParagraph=(body='')=>body.split(/\n\s*\n/).map(part=>part.replace(/^#+\s*/gm,'').trim()).find(Boolean)||''
const sentences=(value:string)=>clean(value).split(/(?<=[.!?])\s+/).filter(Boolean)
const strategy=(seed:VisualStudioContentSeed)=>seed.visual_strategy&&typeof seed.visual_strategy==='object'?seed.visual_strategy:{}
const visualHeadline=(seed:VisualStudioContentSeed)=>clamp(String(strategy(seed).visual_headline||seed.title),100)
const support=(seed:VisualStudioContentSeed)=>clamp(String(strategy(seed).visual_support||sentences(firstParagraph(seed.body||'')).slice(0,2).join(' ')||seed.content_family||'Business decision support'),150)
const titleSize=(w:number,h:number,text:string,factor=1)=>{const base=Math.max(40,Math.min(82,Math.min(w,h)*.061))*factor;const len=clean(text).length;return Math.round(len>115?base*.72:len>80?base*.82:len>55?base*.9:base)}
const supportSize=(w:number,h:number,text='')=>Math.round(Math.max(21,Math.min(text.length>125?29:36,Math.min(w,h)*.028)))
function metric(seed:VisualStudioContentSeed){const source=`${seed.title} ${seed.body||''}`,found=source.match(/(?:[-+]?\d+(?:[.,]\d+)?\s?%|[$€]\s?\d+(?:[.,]\d+)?(?:\s?[KMB])?|\d+(?:[.,]\d+)?x)/i);if(!found)return null;const index=source.indexOf(found[0]),around=source.slice(Math.max(0,index-60),Math.min(source.length,index+found[0].length+85)).replace(found[0],'');return{value:found[0].replace(/\s+/g,' '),label:clamp(around,78)||'Business impact'}}
function steps(seed:VisualStudioContentSeed){const lines=(seed.body||'').split('\n').map(line=>line.trim()).filter(Boolean),bullets=lines.filter(line=>/^[-*•]\s+/.test(line)).map(line=>line.replace(/^[-*•]\s+/,'')),candidates=bullets.length>=3?bullets:sentences(firstParagraph(seed.body||''));return(candidates.length>=3?candidates:['Understand the decision','Choose a proportionate approach','Measure business impact']).slice(0,5).map(item=>clamp(item,62))}
function split(seed:VisualStudioContentSeed){const configured=strategy(seed),left=String(configured.left||''),right=String(configured.right||'');if(left&&right)return{left:clamp(left,85),right:clamp(right,85)};const title=visualHeadline(seed);for(const separator of[' vs. ',' vs ',' versus ',' but ',' not ']){const index=title.toLowerCase().indexOf(separator);if(index>0)return{left:clamp(title.slice(0,index),85),right:clamp(title.slice(index+separator.length),85)}}return{left:clamp(seed.title,85),right:clamp(support(seed),90)}}
function logo(w:number,h:number,dark:boolean):VisualElement{const m=safe(w,h),lw=Math.round(Math.min(360,Math.max(285,w*.29)));return{id:'logo',kind:'logo',role:'brand',x:m,y:m,w:lw,h:Math.round(lw*.28),src:dark?brand.logos.white:brand.logos.horizontal,locked:true}}
function footer(w:number,h:number,dark:boolean):VisualElement{const m=safe(w,h);return{id:'footer',kind:'text',role:'footer',x:m,y:h-m-34,w:w-m*2,h:34,text:`${brand.tagline} · ${brand.website}`,fontSize:Math.max(17,Math.round(w/64)),fontFamily:brand.fonts.body,fontWeight:500,color:dark?brand.colors.mutedOnDark:brand.colors.slate,locked:true}}
function tag(id:string,text:string,x:number,y:number,width:number,dark:boolean):VisualElement{return{id,kind:'tag',x,y,w:width,h:44,text:clean(text).toUpperCase(),fontSize:17,fontFamily:brand.fonts.body,fontWeight:700,color:dark?brand.colors.accentBlue:brand.colors.indigo,fill:dark?brand.colors.navySoft:'#EEF2FF',radius:22,align:'center'}}
function base(seed:VisualStudioContentSeed,key:VisualTemplateKey,formatKey:VisualFormatKey,background:string,elements:VisualElement[],mode?:PublicationMode):VisualDesign{return{name:`${visualHeadline(seed)} · ${VISUAL_TEMPLATES.find(item=>item.key===key)?.label||key}`,templateKey:key,formatKey,publicationMode:mode||seed.publication_mode||'text_with_visual',background,contentId:seed.content_id,elements}}
function insight(seed:VisualStudioContentSeed,formatKey:VisualFormatKey,dark:boolean):VisualDesign{const{width:w,height:h}=fmt(formatKey),m=safe(w,h),headline=visualHeadline(seed),sub=support(seed),elements:VisualElement[]=[logo(w,h,dark)],x=dark?m:m+34;if(dark)elements.push(tag('eyebrow-tag',seed.content_family||'SC-Analytics insight',m,Math.round(h*.21),Math.min(300,w*.32),true));else elements.push({id:'accent',kind:'rect',x:m,y:Math.round(h*.23),w:Math.max(7,w*.008),h:Math.round(h*.43),fill:brand.colors.indigo,radius:4});elements.push({id:'headline',kind:'text',role:'headline',x,y:Math.round(h*.31),w:w-x-m,h:Math.round(h*.32),text:headline,fontSize:titleSize(w,h,headline),fontFamily:brand.fonts.display,fontWeight:650,color:dark?brand.colors.textOnDark:brand.colors.ink});elements.push({id:'support',kind:'text',role:'support',x,y:Math.round(h*.70),w:w-x-m,h:Math.round(h*.12),text:sub,fontSize:supportSize(w,h,sub),fontFamily:brand.fonts.body,fontWeight:400,color:dark?brand.colors.mutedOnDark:brand.colors.slate});elements.push(footer(w,h,dark));return base(seed,dark?'insight_dark':'insight_light',formatKey,dark?brand.colors.navy:brand.colors.paper,elements)}
function metricFocus(seed:VisualStudioContentSeed,formatKey:VisualFormatKey):VisualDesign{const{width:w,height:h}=fmt(formatKey),m=safe(w,h),headline=visualHeadline(seed),sub=support(seed),mt=metric(seed)||{value:'01',label:seed.content_family||'Decision insight'};return base(seed,'metric_focus',formatKey,brand.colors.navy,[logo(w,h,true),{id:'headline',kind:'text',role:'headline',x:m,y:Math.round(h*.23),w:w-m*2,h:Math.round(h*.15),text:headline,fontSize:titleSize(w,h,headline,.7),fontFamily:brand.fonts.display,fontWeight:650,color:brand.colors.textOnDark},{id:'metric-box',kind:'rect',x:m,y:Math.round(h*.44),w:w-m*2,h:Math.round(h*.31),fill:brand.colors.navyPanel,stroke:brand.colors.line,strokeWidth:2,radius:28},{id:'metric-value',kind:'metric',role:'metric',x:m+34,y:Math.round(h*.49),w:Math.round((w-m*2)*.42),h:Math.round(h*.18),value:mt.value,label:mt.label,fontSize:Math.round(Math.min(w,h)*.115),fontFamily:brand.fonts.body,fontWeight:760,color:brand.colors.accentBlue},{id:'support',kind:'text',role:'support',x:Math.round(w*.53),y:Math.round(h*.50),w:w-Math.round(w*.53)-m-18,h:Math.round(h*.19),text:sub,fontSize:supportSize(w,h,sub),fontFamily:brand.fonts.body,color:brand.colors.mutedOnDark},footer(w,h,true)])}
function comparison(seed:VisualStudioContentSeed,formatKey:VisualFormatKey):VisualDesign{const{width:w,height:h}=fmt(formatKey),m=safe(w,h),gap=Math.round(w*.025),col=Math.round((w-m*2-gap)/2),parts=split(seed),headline=visualHeadline(seed);return base(seed,'comparison_split',formatKey,brand.colors.paper,[logo(w,h,false),{id:'headline',kind:'text',role:'headline',x:m,y:Math.round(h*.20),w:w-m*2,h:Math.round(h*.14),text:headline,fontSize:titleSize(w,h,headline,.62),fontFamily:brand.fonts.display,fontWeight:650,color:brand.colors.ink},{id:'left-box',kind:'rect',x:m,y:Math.round(h*.41),w:col,h:Math.round(h*.38),fill:'#EEF2F7',stroke:brand.colors.lineLight,strokeWidth:2,radius:24},{id:'right-box',kind:'rect',x:m+col+gap,y:Math.round(h*.41),w:col,h:Math.round(h*.38),fill:'#EEF2FF',stroke:'#C7D2FE',strokeWidth:2,radius:24},tag('left-tag','Common framing',m+24,Math.round(h*.45),Math.min(230,col-48),false),tag('right-tag','Better framing',m+col+gap+24,Math.round(h*.45),Math.min(230,col-48),false),{id:'left-text',kind:'text',x:m+28,y:Math.round(h*.56),w:col-56,h:Math.round(h*.18),text:parts.left,fontSize:supportSize(w,h,parts.left)+2,fontFamily:brand.fonts.body,fontWeight:600,color:brand.colors.slate},{id:'right-text',kind:'text',x:m+col+gap+28,y:Math.round(h*.56),w:col-56,h:Math.round(h*.18),text:parts.right,fontSize:supportSize(w,h,parts.right)+2,fontFamily:brand.fonts.body,fontWeight:650,color:brand.colors.indigo},footer(w,h,false)])}
function processDesign(seed:VisualStudioContentSeed,formatKey:VisualFormatKey):VisualDesign{const{width:w,height:h}=fmt(formatKey),m=safe(w,h),list=steps(seed),headline=visualHeadline(seed),elements:VisualElement[]=[logo(w,h,true),{id:'headline',kind:'text',role:'headline',x:m,y:Math.round(h*.20),w:w-m*2,h:Math.round(h*.14),text:headline,fontSize:titleSize(w,h,headline,.62),fontFamily:brand.fonts.display,fontWeight:650,color:brand.colors.textOnDark}];if(h>w*1.1){const y0=Math.round(h*.38),sh=Math.round((h*.42)/list.length);list.forEach((text,i)=>{elements.push({id:`step-dot-${i}`,kind:'rect',x:m,y:y0+i*sh+6,w:40,h:40,fill:brand.colors.accentBlue,radius:20});elements.push({id:`step-${i}`,kind:'text',x:m+64,y:y0+i*sh,w:w-m*2-64,h:sh-6,text,fontSize:supportSize(w,h,text),fontFamily:brand.fonts.body,fontWeight:550,color:brand.colors.textOnDark})})}else{const y0=Math.round(h*.45),gap=Math.round(w*.016),sw=Math.round((w-m*2-gap*(list.length-1))/list.length);list.forEach((text,i)=>{const x=m+i*(sw+gap);elements.push({id:`step-box-${i}`,kind:'rect',x,y:y0,w:sw,h:Math.round(h*.29),fill:i===list.length-1?brand.colors.navySoft:brand.colors.navyPanel,stroke:brand.colors.line,strokeWidth:2,radius:22});elements.push({id:`step-${i}`,kind:'text',x:x+20,y:y0+55,w:sw-40,h:Math.round(h*.16),text,fontSize:Math.max(19,supportSize(w,h,text)-4),fontFamily:brand.fonts.body,fontWeight:550,color:brand.colors.textOnDark})})}elements.push(footer(w,h,true));return base(seed,'process_steps',formatKey,brand.colors.navy,elements)}
function caseResult(seed:VisualStudioContentSeed,formatKey:VisualFormatKey):VisualDesign{const{width:w,height:h}=fmt(formatKey),m=safe(w,h),mt=metric(seed),headline=visualHeadline(seed),sub=support(seed);return base(seed,'case_result',formatKey,brand.colors.paper,[logo(w,h,false),tag('case-tag','Business case',m,Math.round(h*.20),210,false),{id:'headline',kind:'text',role:'headline',x:m,y:Math.round(h*.30),w:w-m*2,h:Math.round(h*.18),text:headline,fontSize:titleSize(w,h,headline,.64),fontFamily:brand.fonts.display,fontWeight:650,color:brand.colors.ink},{id:'problem',kind:'text',x:m,y:Math.round(h*.58),w:Math.round(w*.44),h:Math.round(h*.16),text:sub,fontSize:supportSize(w,h,sub),fontFamily:brand.fonts.body,color:brand.colors.slate},{id:'result-box',kind:'rect',x:Math.round(w*.57),y:Math.round(h*.54),w:w-Math.round(w*.57)-m,h:Math.round(h*.25),fill:brand.colors.navy,radius:24},{id:'result',kind:'metric',x:Math.round(w*.60),y:Math.round(h*.58),w:w-Math.round(w*.60)-m-20,h:Math.round(h*.17),value:mt?.value||'DECIDE',label:mt?.label||'A clearer decision system',fontSize:Math.round(Math.min(w,h)*.07),fontFamily:brand.fonts.body,fontWeight:800,color:brand.colors.accentBlue},footer(w,h,false)])}
function article(seed:VisualStudioContentSeed,formatKey:VisualFormatKey):VisualDesign{const{width:w,height:h}=fmt(formatKey),m=safe(w,h),headline=visualHeadline(seed),sub=support(seed);return base(seed,'article_editorial',formatKey,brand.colors.navy,[logo(w,h,true),{id:'eyebrow',kind:'text',x:m,y:Math.round(h*.25),w:w-m*2,h:36,text:`${(seed.content_family||'KNOWLEDGE').toUpperCase()} · ${(seed.language||'EN').toUpperCase()}`,fontSize:20,fontFamily:brand.fonts.body,fontWeight:750,color:brand.colors.accentBlue},{id:'headline',kind:'text',role:'headline',x:m,y:Math.round(h*.35),w:Math.round(w*.74),h:Math.round(h*.31),text:headline,fontSize:titleSize(w,h,headline,.76),fontFamily:brand.fonts.display,fontWeight:650,color:brand.colors.textOnDark},{id:'support',kind:'text',x:m,y:Math.round(h*.73),w:Math.round(w*.70),h:Math.round(h*.10),text:sub,fontSize:supportSize(w,h,sub),fontFamily:brand.fonts.body,color:brand.colors.mutedOnDark},{id:'graphic',kind:'rect',x:Math.round(w*.82),y:Math.round(h*.29),w:Math.round(w*.10),h:Math.round(h*.47),fill:brand.colors.navyPanelAlt,stroke:brand.colors.line,strokeWidth:2,radius:28},footer(w,h,true)])}
function imageLed(seed:VisualStudioContentSeed,formatKey:VisualFormatKey):VisualDesign{const{width:w,height:h}=fmt(formatKey),m=safe(w,h),headline=visualHeadline(seed),sub=support(seed);return base(seed,'image_only_statement',formatKey,brand.colors.navy,[logo(w,h,true),{id:'frame',kind:'rect',x:m,y:Math.round(h*.21),w:w-m*2,h:Math.round(h*.60),fill:brand.colors.navyPanel,stroke:brand.colors.line,strokeWidth:2,radius:30},{id:'statement',kind:'text',role:'headline',x:m+42,y:Math.round(h*.30),w:w-m*2-84,h:Math.round(h*.30),text:headline,fontSize:titleSize(w,h,headline,.86),fontFamily:brand.fonts.display,fontWeight:650,color:brand.colors.textOnDark},{id:'support',kind:'text',x:m+42,y:Math.round(h*.67),w:w-m*2-84,h:Math.round(h*.09),text:sub,fontSize:supportSize(w,h,sub),fontFamily:brand.fonts.body,color:brand.colors.mutedOnDark},footer(w,h,true)],'image_only')}
export function createDesignFromTemplate(key:VisualTemplateKey,formatKey:VisualFormatKey,seed:VisualStudioContentSeed):VisualDesign{if(key==='insight_light')return insight(seed,formatKey,false);if(key==='metric_focus')return metricFocus(seed,formatKey);if(key==='comparison_split')return comparison(seed,formatKey);if(key==='process_steps')return processDesign(seed,formatKey);if(key==='case_result')return caseResult(seed,formatKey);if(key==='article_editorial')return article(seed,formatKey);if(key==='image_only_statement')return imageLed(seed,formatKey);return insight(seed,formatKey,true)}
export function recommendTemplates(seed:VisualStudioContentSeed):VisualTemplateKey[]{const configured=String(strategy(seed).visual_type||'').toLowerCase(),source=`${seed.title} ${seed.body||''}`.toLowerCase(),result:VisualTemplateKey[]=[];if(configured==='metric'||metric(seed))result.push('metric_focus','case_result');if(configured==='comparison'||/\b(vs\.?|versus|before|after|instead|rather than|trade-?off)\b/i.test(source))result.push('comparison_split');if(configured==='process'||/\b(process|framework|steps?|workflow|system|sequence|decision|pipeline)\b/i.test(source))result.push('process_steps');if(['statement','contrarian','question'].includes(configured))result.push('image_only_statement');if(seed.content_type==='article')result.push('article_editorial');result.push('insight_dark','insight_light','image_only_statement');return Array.from(new Set(result)).slice(0,4)}
export function adaptDesignToFormat(design:VisualDesign,formatKey:VisualFormatKey):VisualDesign{const old=fmt(design.formatKey),next=fmt(formatKey),sx=next.width/old.width,sy=next.height/old.height,fs=Math.sqrt(sx*sy);return{...design,formatKey,elements:design.elements.map(el=>({...el,x:Math.round(el.x*sx),y:Math.round(el.y*sy),w:Math.round(el.w*sx),h:Math.round(el.h*sy),fontSize:el.fontSize?Math.max(12,Math.round(el.fontSize*fs)):el.fontSize,strokeWidth:el.strokeWidth?Math.max(1,Math.round(el.strokeWidth*fs)):el.strokeWidth,radius:el.radius?Math.round(el.radius*fs):el.radius}))}}
let elementSequence=0;const uid=(prefix:string)=>`${prefix}-${Date.now()}-${++elementSequence}`
export function duplicateElement(el:VisualElement):VisualElement{return{...el,id:uid(`${el.id}-copy`),x:el.x+24,y:el.y+24,locked:false,role:el.role==='brand'?undefined:el.role}}
export function emptyTextElement(formatKey:VisualFormatKey):VisualElement{const{width:w,height:h}=fmt(formatKey);return{id:uid('text'),kind:'text',x:Math.round(w*.12),y:Math.round(h*.45),w:Math.round(w*.50),h:Math.round(h*.16),text:'New text',fontSize:Math.round(Math.min(w,h)*.04),fontFamily:brand.fonts.body,fontWeight:500,color:brand.colors.textOnDark}}
export function emptyMetricElement(formatKey:VisualFormatKey):VisualElement{const{width:w,height:h}=fmt(formatKey);return{id:uid('metric'),kind:'metric',x:Math.round(w*.12),y:Math.round(h*.45),w:Math.round(w*.40),h:Math.round(h*.20),value:'42%',label:'Metric label',fontSize:Math.round(Math.min(w,h)*.10),fontFamily:brand.fonts.body,fontWeight:800,color:brand.colors.accentBlue}}
export function emptyRectElement(formatKey:VisualFormatKey):VisualElement{const{width:w,height:h}=fmt(formatKey);return{id:uid('rect'),kind:'rect',x:Math.round(w*.20),y:Math.round(h*.36),w:Math.round(w*.42),h:Math.round(h*.24),fill:brand.colors.navyPanel,stroke:brand.colors.line,strokeWidth:2,radius:24,opacity:1}}
export function emptyLineElement(formatKey:VisualFormatKey):VisualElement{const{width:w,height:h}=fmt(formatKey);return{id:uid('line'),kind:'line',x:Math.round(w*.20),y:Math.round(h*.52),w:Math.round(w*.40),h:0,stroke:brand.colors.accentBlue,strokeWidth:4,opacity:1}}
export function emptyLogoElement(formatKey:VisualFormatKey):VisualElement{const{width:w,height:h}=fmt(formatKey);return{...logo(w,h,true),id:uid('logo'),role:undefined,locked:false}}
export{PUBLICATION_MODES,VISUAL_FORMATS,SC_BRAND}
