import { randomUUID } from 'node:crypto'
import { NextResponse } from 'next/server'
import { getContentItem, insertGrowthRow, isGrowthAdminAuthenticated, queryGrowthTable, updateGrowthRow, type GrowthApproval, type GrowthTask } from '@/lib/growth-admin'
import { mutateGrowthRpc } from '@/lib/supabase-growth'
import { dispatchOperatorQueue } from '@/lib/github-actions'
export async function POST(request:Request){if(!(await isGrowthAdminAuthenticated()))return new NextResponse('Unauthorized',{status:401});const form=await request.formData(),contentId=String(form.get('content_id')||'').trim(),returnTo=String(form.get('return_to')||`/growth-admin/preview/${encodeURIComponent(contentId)}#decision`);if(!contentId)return new NextResponse('Missing content_id',{status:400});const item=await getContentItem(contentId);if(!item)return new NextResponse('Content not found',{status:404});if(item.visual_strategy?.publisher==='editorial_edge'){
const approved=await queryGrowthTable<GrowthApproval>('approvals',{target_id:`eq.${contentId}`,action_type:'eq.publish_editorial',status:'eq.approved'},{cacheSeconds:0});
if(!approved.length)return new NextResponse('Approve the publication before publishing',{status:409});
const jobs=await queryGrowthTable<{state:string}>('editorial_publication_jobs',{content_id:`eq.${contentId}`,limit:'1'},{cacheSeconds:0});
if(jobs.some(job=>['publishing','published','uncertain'].includes(job.state)))return new NextResponse('Inspect the existing publication result before retrying',{status:409});
await updateGrowthRow('content_items','content_id',contentId,{status:'scheduled',scheduled_at:new Date().toISOString(),visual_strategy:{...item.visual_strategy,test_reserved:false}});
await updateGrowthRow('editorial_publication_jobs','content_id',contentId,{attempts:0,next_attempt_at:null,last_error:null});
const requestId=await mutateGrowthRpc<number>('editorial_request_tick',{p_dry_run:false,p_content_id:contentId});
const target=new URL(`/growth-admin/preview/${encodeURIComponent(contentId)}`,request.url);target.searchParams.set('editorial_request',String(requestId));return NextResponse.redirect(target,303);
}if(item.status==='published')return NextResponse.redirect(new URL(returnTo,request.url),303);const type=String(item.content_type||'').toLowerCase(),channel=String(item.channel||'').toLowerCase(),linkedinArticle=type==='linkedin_article'||(type==='article'&&channel.includes('linkedin'));if(linkedinArticle)return new NextResponse('LinkedIn articles are tracked as a distinct format and require a dedicated publishing flow; they are not sent through the normal LinkedIn post publisher.',{status:409});const websiteArticle=type==='article'||type==='web_article';const approvals=await queryGrowthTable<GrowthApproval>('approvals',{target_id:`eq.${contentId}`,status:'eq.approved',order:'decided_at.desc',limit:'10'},{cacheSeconds:0}),expectedType=websiteArticle?'publish_article':'publish_post';if(!approvals.some(row=>row.action_type===expectedType))return new NextResponse('Content has not been approved for publication',{status:409});await updateGrowthRow('content_items','content_id',contentId,{scheduled_at:null,status:'approved'});const taskType=websiteArticle?'OPERATOR_PUBLISH_ARTICLE':'OPERATOR_PUBLISH_LINKEDIN',recent=await queryGrowthTable<GrowthTask>('tasks',{tenant_id:'eq.sc-analytics',type:`eq.${taskType}`,order:'created_at.desc',limit:'5'},{cacheSeconds:0}),duplicate=recent.find(task=>['queued','pending','running'].includes(String(task.status||''))&&String(task.inputs?.content_id||'')===contentId&&Date.now()-Date.parse(String(task.created_at||''))<=30000),taskId=duplicate?.task_id||`task_${randomUUID().replaceAll('-','').slice(0,12)}`;if(!duplicate){const now=new Date().toISOString();await insertGrowthRow('tasks',{task_id:taskId,tenant_id:'sc-analytics',type:taskType,scheduled_for:now,status:'queued',requires_approval:false,inputs:{content_id:contentId},outputs:{},created_at:now})}const dispatch=await dispatchOperatorQueue(taskId),url=new URL(returnTo.startsWith('/')?returnTo:`/growth-admin/preview/${encodeURIComponent(contentId)}#decision`,request.url);url.searchParams.set('queued',taskId);url.searchParams.set('dispatched',dispatch.dispatched?'1':'0');url.searchParams.set('deduplicated',duplicate?'1':'0');if(!dispatch.dispatched)url.searchParams.set('dispatch_reason',dispatch.reason);return NextResponse.redirect(url,303)}
