import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { queryGrowthTable } from '@/lib/supabase-growth'

export const dynamic='force-dynamic';export const revalidate=0
type SeoPage={slug:string;primary_keyword:string;secondary_keywords?:string[];title:string;meta_description:string;h1:string;intro:string;sections?:Array<{heading?:string;body?:string}>;cta_title?:string;cta_body?:string;internal_links?:Array<{href?:string;label?:string}>;status:string}
async function getPage(slug:string){try{return(await queryGrowthTable<SeoPage>('seo_pages',{tenant_id:'eq.sc-analytics',slug:`eq.${slug}`,status:'eq.published',limit:'1'},{cacheSeconds:0}))[0]||null}catch(error){console.error('SEO service page unavailable',{slug,error:error instanceof Error?error.message:String(error)});return null}}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params,row=await getPage(slug);if(!row)return{};return{title:row.title,description:row.meta_description,keywords:[row.primary_keyword,...(row.secondary_keywords||[])],alternates:{canonical:`/services/${row.slug}`},openGraph:{title:row.title,description:row.meta_description,url:`https://sc-analytics.io/services/${row.slug}`,type:'website'}}}
export default async function SeoServicePage({params}:{params:Promise<{slug:string}>}){const{slug}=await params,row=await getPage(slug);if(!row)notFound();return <main className="bg-white text-slate-950"><section className="border-b border-slate-200 bg-slate-950 text-white"><div className="mx-auto max-w-6xl px-6 py-24"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-indigo-300">SC-Analytics · Services</p><h1 className="mt-5 max-w-4xl text-5xl leading-tight md:text-6xl" style={{fontFamily:'var(--font-playfair)'}}>{row.h1}</h1><div className="mt-7 max-w-3xl whitespace-pre-wrap text-lg leading-8 text-slate-300">{row.intro}</div></div></section><section className="mx-auto max-w-6xl px-6 py-20"><div className="grid gap-12">{(row.sections||[]).map((section,index)=><article key={`${section.heading}-${index}`} className="grid gap-4 border-b border-slate-200 pb-12 md:grid-cols-[0.38fr_0.62fr]"><h2 className="text-2xl md:text-3xl" style={{fontFamily:'var(--font-playfair)'}}>{section.heading}</h2><p className="whitespace-pre-wrap text-base leading-8 text-slate-600">{section.body}</p></article>)}</div>{(row.internal_links||[]).length>0&&<div className="mt-12 flex flex-wrap gap-2">{row.internal_links?.map((link,index)=><Link key={`${link.href}-${index}`} href={link.href||'/services'} className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50">{link.label||'Learn more'}</Link>)}</div>}</section><section className="border-t border-slate-200 bg-indigo-50"><div className="mx-auto max-w-6xl px-6 py-16 md:flex md:items-end md:justify-between"><div><h2 className="text-3xl" style={{fontFamily:'var(--font-playfair)'}}>{row.cta_title||'Talk through the decision'}</h2><p className="mt-4 max-w-2xl text-base leading-8 text-slate-600">{row.cta_body}</p></div><Link href="/contact" className="mt-6 rounded-lg bg-slate-950 px-5 py-3 text-sm font-semibold text-white md:mt-0">Contact SC-Analytics</Link></div></section></main>}
