'use client'
import { parseControlCenterDateTime, toControlCenterDateTimeLocal } from '@/lib/control-center-time'
import { useCallback, useEffect, useState } from 'react'
import { Badge, EmptyState, PageHeader, StatCard, adminButtonPrimary, adminButtonSecondary, adminInput, adminPanel } from './AdminUi'
type Company = { id: string; name: string; domain?: string; email?:string; website?:string; relationship_type?: string; commercial_status?: string; contact_status?: string; email_status?: string; brief?: string; proposed_value?: string; next_step?: string; next_step_at?: string; exclude_from_discovery?: boolean }
type Person = { id: string; company_id: string; name: string; role?: string; email?: string; linkedin_url?: string; linkedin_status?: string }
type Event = { id: string; company_id: string; person_id?: string; channel?: string; direction?: string; event_type?: string; summary: string; occurred_at?: string; evidence_url?: string; source?: string }
type Snapshot = { companies: Company[]; people: Person[]; events: Event[]; configured?: boolean; totals?: {companies:number;people:number;events:number}; limit?:number; error?: string; preferences?: Record<string,unknown>; sync_runs?: Array<{id:string;account_email?:string;status?:string;started_at?:string;processed_count?:number;error?:string}> }
const relationships: Record<string,string> = { unknown: 'Por definir', direct_client: 'Cliente directo', referral_partner: 'Partner de referidos', technical_partner: 'Colaboración técnica', delivery_partner: 'Partner de implementación', hiring_alternative: 'Alternativa a contratación' }
const stages: Record<string,string> = { discovered: 'Por explorar', researched: 'Investigada', qualified: 'Cualificada', contacted: 'Contactada', awaiting_reply: 'Esperando respuesta', conversation: 'En conversación', meeting_booked: 'Llamada confirmada', excluded: 'Excluida', replied: 'Ha respondido', meeting_pending: 'Llamada por acordar', meeting_scheduled: 'Llamada confirmada', proposal: 'Propuesta', won: 'Colaboración activa', lost: 'Descartada', not_now: 'Más adelante' }
const emailStates: Record<string,string> = { unknown: 'Sin revisar', pending_reply: 'Nos toca responder', waiting_reply: 'Esperando respuesta', auto_reply: 'Respuesta automática', no_reply_needed: 'Sin acción pendiente', bounced: 'Dirección incorrecta' }
const linkedStates: Record<string,string> = { unknown: 'Sin confirmar', not_sent: 'Sin invitación', invitation_sent: 'Invitación enviada', connected: 'Conectados', declined: 'Declinada' }
const initial: Snapshot = { companies: [], people: [], events: [] }
function safeUrl(value?: string) { if (!value) return undefined; try { const url = new URL(value); return ['https:','http:'].includes(url.protocol) ? value : undefined } catch { return undefined } }
function date(value?: string) { return value ? new Date(value).toLocaleString('es-ES', { timeZone: 'Europe/Madrid', dateStyle: 'medium', timeStyle: 'short' }) : 'Fecha sin confirmar' }
export default function CommercialMemoryWorkspace() {
 const [data,setData] = useState<Snapshot>(initial), [loading,setLoading] = useState(true), [error,setError] = useState(''), [notice,setNotice] = useState(''), [busy,setBusy] = useState(false)
 const [syncReport,setSyncReport] = useState<{accounts:Array<{account:string;linked:number;unmatched:number;messages:number;complete:boolean;errors:string[];finished_at:string}>;complete:boolean;readonly:boolean}|null>(null)
 const [search,setSearch] = useState(''), [relationship,setRelationship] = useState(''), [contact,setContact] = useState(''), [stage,setStage] = useState(''), [selected,setSelected] = useState(''), [showNew,setShowNew] = useState(false)
 const refresh = useCallback(async () => { setLoading(true); try { const response = await fetch('/api/growth-admin/commercial-memory', { cache:'no-store' }); const result = await response.json(); if (!response.ok || result.error) throw new Error(result.error || 'No se ha podido cargar la memoria.'); setData(result); setError('') } catch (e) { setError(e instanceof Error ? e.message : 'Error de conexión') } finally { setLoading(false) } }, [])
 useEffect(() => { void refresh() }, [refresh])
 async function save(payload: Record<string,unknown>) { setBusy(true); setError(''); setNotice(''); try { const response = await fetch('/api/growth-admin/commercial-memory', { method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload) }); const result = await response.json(); if (!response.ok || result.error) throw new Error(result.error || 'No se ha podido guardar.'); setNotice('Cambios guardados en la memoria comercial.'); await refresh(); return true } catch(e) { setError(e instanceof Error ? e.message : 'Error al guardar'); return false } finally { setBusy(false) } }
 async function syncGmail() { setBusy(true); setSyncReport(null); setError(''); try { const response = await fetch('/api/growth-admin/commercial-memory/sync', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({days:14,limit:40})}); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'No se ha podido revisar Gmail'); setSyncReport(result); await refresh() } catch(e) {setError(e instanceof Error ? e.message : 'Error de sincronización')} finally {setBusy(false)} }
 const filtered = data.companies.filter(c => (!search || `${c.name} ${c.domain || ''} ${c.brief || ''}`.toLowerCase().includes(search.toLowerCase())) && (!relationship || c.relationship_type === relationship) && (!stage || c.commercial_status === stage) && (!contact || (contact === 'contacted' ? ['contacted','replied'].includes(c.contact_status || '') : !['contacted','replied','do_not_contact'].includes(c.contact_status || ''))))
 const company = data.companies.find(c => c.id === selected)
 const people = data.people.filter(p => p.company_id === selected)
 const events = data.events.filter(e => e.company_id === selected).sort((a,b) => (b.occurred_at || '').localeCompare(a.occurred_at || ''))
 return <>
  <PageHeader eyebrow="Prospección y relaciones" title="Memoria comercial" description="Empresas, personas y conversaciones en un mismo historial. Cada nuevo contacto parte de lo que ya sabemos." actions={<><button onClick={()=>void syncGmail()} disabled={busy} className="rounded-lg border border-indigo-400 bg-indigo-900 px-4 py-2.5 text-sm font-semibold text-white">Revisar Gmail</button><button onClick={() => void refresh()} disabled={loading} className={adminButtonSecondary}>Actualizar</button><button onClick={() => setShowNew(!showNew)} className="rounded-lg bg-indigo-500 px-4 py-2.5 text-sm font-semibold text-white">Añadir empresa</button></>} />
  {error && <div role="alert" className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{error}</div>}
  {notice && <div role="status" className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</div>}
  {syncReport && <section className={`${adminPanel} mb-5 p-5`}><h2 className="text-sm font-semibold">{syncReport.complete ? 'Revisión terminada' : 'Revisión parcial'}</h2><p className="mt-2 text-xs leading-5 text-slate-500">Últimos 14 días, hasta 40 conversaciones por cuenta. Se ha leído Gmail y actualizado el historial del CMI; esta acción no envía ni modifica correos.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{syncReport.accounts.map(account=><div key={account.account} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-2"><strong className="break-all text-sm">{account.account}</strong><Badge tone={account.complete?'green':'amber'}>{account.complete?'Revisada':'Parcial'}</Badge></div><p className="mt-3 text-sm text-slate-600">{account.messages} mensajes revisados · {account.linked} vinculados · {account.unmatched} sin empresa identificada</p>{account.errors.length > 0 && <ul className="mt-3 space-y-1 text-xs text-rose-700">{account.errors.map((message,index)=><li key={index}>{message}</li>)}</ul>}<p className="mt-2 text-xs text-slate-400">{date(account.finished_at)}</p></div>)}</div></section>}
  <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Empresas registradas" value={data.totals?.companies ?? data.companies.length}/><StatCard label="Nos toca responder" value={data.companies.filter(c => c.email_status === 'pending_reply').length} tone="amber"/><StatCard label="Conexiones confirmadas" value={data.people.filter(p => p.linkedin_status === 'connected').length} note="Estado registrado en el historial" tone="blue"/><StatCard label="Excluidas de nueva búsqueda" value={data.companies.filter(c => c.exclude_from_discovery).length} tone="violet"/></div>
  <details className={`${adminPanel} mb-6 p-5`}><summary className="cursor-pointer text-sm font-semibold">Criterios comerciales y forma de trabajar</summary><div className="mt-4 grid gap-4 text-sm leading-6 text-slate-600 md:grid-cols-3"><p><strong className="text-slate-900">Primer contacto</strong><br/>Presentación cercana y personalizada. Colaboración con el equipo destinatario y llamada de 30 minutos sin compromiso.</p><p><strong className="text-slate-900">Segmentos</strong><br/>Clientes directos, referidos, colaboración técnica, implementación y alternativa externa a contratación. Cada relación mantiene su propio enfoque.</p><p><strong className="text-slate-900">Upwork</strong><br/>Perfil personal de Arnau, experiencia y portfolio relevantes. Objetivo de 50–60 USD/h; prioridad Europa, Estados Unidos, Australia y Nueva Zelanda.</p></div></details>
  {showNew && <form className={`${adminPanel} mb-6 grid gap-3 p-5 md:grid-cols-3`} onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); if (await save({action:'company',name:f.get('name'),domain:f.get('domain'),relationship_type:f.get('relationship_type'),brief:f.get('brief')})) setShowNew(false) }}><label className="text-xs font-semibold">Empresa<input name="name" required maxLength={200} className={`${adminInput} mt-2 w-full`} /></label><label className="text-xs font-semibold">Dominio<input name="domain" placeholder="empresa.com" className={`${adminInput} mt-2 w-full`}/></label><label className="text-xs font-semibold">Tipo de relación<select name="relationship_type" className={`${adminInput} mt-2 w-full`}>{Object.entries(relationships).map(([v,label]) => <option key={v} value={v}>{label}</option>)}</select></label><label className="text-xs font-semibold md:col-span-3">Brief<textarea name="brief" className={`${adminInput} mt-2 w-full`} placeholder="Qué hace la empresa, señal observada y posible encaje"/></label><button disabled={busy} className={adminButtonPrimary}>Guardar empresa</button></form>}
  <div className={`${adminPanel} mb-6 flex flex-wrap gap-3 p-4`}><input aria-label="Buscar empresa" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar empresa, dominio o brief" className={`${adminInput} min-w-56 flex-1`}/><select aria-label="Tipo de relación" className={adminInput} value={relationship} onChange={e=>setRelationship(e.target.value)}><option value="">Todas las relaciones</option>{Object.entries(relationships).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="Contacto" className={adminInput} value={contact} onChange={e=>setContact(e.target.value)}><option value="">Con y sin contacto</option><option value="contacted">Ya contactadas</option><option value="uncontacted">Sin contacto registrado</option></select><select aria-label="Etapa comercial" className={adminInput} value={stage} onChange={e=>setStage(e.target.value)}><option value="">Todas las etapas</option>{Object.entries(stages).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>
  <div className="grid items-start gap-6 xl:grid-cols-[minmax(320px,0.9fr)_minmax(0,1.5fr)]"><section className={`${adminPanel} overflow-hidden`}><div className="border-b border-slate-200 p-5"><h2 className="text-lg font-semibold">Empresas <span className="text-slate-400">{filtered.length}</span></h2><p className="mt-1 text-xs text-slate-500">Los registros excluidos permanecen visibles para seguimiento.{data.totals && data.totals.companies > data.companies.length && ` Mostrando las ${data.companies.length} empresas más recientes de ${data.totals.companies}.`}</p></div>{loading && !data.companies.length ? <p className="p-6 text-sm text-slate-500">Cargando historial…</p> : filtered.length ? <div className="max-h-[760px] overflow-y-auto">{filtered.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} className={`block w-full border-b border-slate-100 p-5 text-left last:border-b-0 ${selected===c.id?'bg-indigo-50':'hover:bg-slate-50'}`}><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-semibold">{c.name}</span><Badge tone={['contacted','replied'].includes(c.contact_status || '')?'blue':'slate'}>{['contacted','replied'].includes(c.contact_status || '')?'Contactada':'Sin contacto'}</Badge></div><p className="mt-2 text-xs text-slate-600">{relationships[c.relationship_type || ''] || 'Relación por definir'} · {stages[c.commercial_status || ''] || c.commercial_status || 'Por explorar'}</p>{c.brief && <p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{c.brief}</p>}<div className="mt-3 flex flex-wrap gap-2">{c.exclude_from_discovery && <Badge>Excluir de nuevas búsquedas</Badge>}{c.email_status && c.email_status!=='unknown' && <Badge tone={c.email_status==='pending_reply'?'amber':'slate'}>{emailStates[c.email_status] || c.email_status}</Badge>}</div></button>)}</div>:<div className="p-5"><EmptyState>{data.companies.length?'Ninguna empresa coincide con estos filtros.':'Todavía no hay empresas registradas. Añade la primera o importa el historial desde el operador.'}</EmptyState></div>}</section>
  <section>{company ? <div className="space-y-5"><div className={`${adminPanel} p-6`}><h2 className="text-2xl font-semibold">{company.name}</h2><p className="mt-1 text-sm text-slate-500">{company.domain}</p><div className="mt-3 flex flex-wrap gap-3 text-xs font-semibold text-indigo-700">{safeUrl(company.website) && <a href={safeUrl(company.website)} target="_blank" rel="noopener noreferrer">Ver web ↗</a>}{company.email && <a href={`mailto:${company.email}`}>{company.email}</a>}</div><form key={company.id} className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await save({action:'patch',entity:'company',id:company.id,patch:{relationship_type:f.get('relationship_type'),commercial_status:f.get('commercial_status'),contact_status:f.get('contact_status'),email_status:f.get('email_status'),brief:f.get('brief'),proposed_value:f.get('proposed_value'),next_step:f.get('next_step'),next_step_at:f.get('next_step_at') ? parseControlCenterDateTime(String(f.get('next_step_at'))).toISOString() : null,exclude_from_discovery:f.get('exclude_from_discovery')==='on'}})}}>{[['relationship_type','Relación',relationships],['commercial_status','Etapa comercial',stages],['contact_status','Contacto',{uncontacted:'Sin contacto',not_contacted:'Sin contacto registrado',contacted:'Contactada',replied:'Ha respondido',do_not_contact:'No contactar'}],['email_status','Estado del correo',emailStates]].map(([key,label,options])=><label key={String(key)} className="text-xs font-semibold">{String(label)}<select name={String(key)} defaultValue={String(company[key as keyof Company] || (key==='contact_status'?'uncontacted':key==='commercial_status'?'discovered':'unknown'))} className={`${adminInput} mt-2 w-full`}>{Object.entries(options).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>)}{[['brief','Brief de la empresa'],['proposed_value','Qué hemos planteado'],['next_step','Siguiente paso']].map(([key,label])=><label key={key} className="text-xs font-semibold sm:col-span-2">{label}<textarea name={key} defaultValue={String(company[key as keyof Company] || '')} className={`${adminInput} mt-2 w-full`} rows={2}/></label>)}<label className="text-xs font-semibold sm:col-span-2">Fecha del siguiente paso (hora de Barcelona)<input type="datetime-local" name="next_step_at" defaultValue={toControlCenterDateTimeLocal(company.next_step_at)} className={`${adminInput} mt-2 w-full`}/></label><label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" name="exclude_from_discovery" defaultChecked={company.exclude_from_discovery}/>Excluir de nuevas búsquedas; conservar para seguimiento</label><button disabled={busy} className={adminButtonPrimary}>Guardar ficha</button></form></div>
  <div className={`${adminPanel} p-6`}><h3 className="text-lg font-semibold">Personas y LinkedIn</h3><p className="mt-2 text-xs leading-5 text-slate-500">El estado de conexión se registra cuando Arnau lo confirma. Una invitación enviada no equivale a una conexión aceptada.</p>{people.map(p=><div key={p.id} className="mt-4 rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{p.name}</p><p className="mt-1 text-xs text-slate-500">{p.role}</p>{p.email && <a href={`mailto:${p.email}`} className="mt-1 block break-all text-xs text-indigo-700">{p.email}</a>}</div>{safeUrl(p.linkedin_url) && <a href={safeUrl(p.linkedin_url)} target="_blank" rel="noopener noreferrer" className={adminButtonSecondary}>Abrir LinkedIn ↗</a>}</div><label className="mt-3 block text-xs font-semibold">Estado manual<select aria-label={`Estado LinkedIn de ${p.name}`} value={p.linkedin_status || 'unknown'} disabled={busy} onChange={e=>void save({action:'patch',entity:'person',id:p.id,patch:{linkedin_status:e.target.value}})} className={`${adminInput} ml-3`}>{Object.entries(linkedStates).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div>)}<form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(await save({action:'person',company_id:company.id,name:f.get('name'),role:f.get('role'),email:f.get('email'),linkedin_url:f.get('linkedin_url')}))form.reset()}}><input name="name" required aria-label="Nombre de persona" placeholder="Nombre" className={adminInput}/><input name="role" aria-label="Cargo" placeholder="Cargo" className={adminInput}/><input name="email" type="email" aria-label="Correo de persona" placeholder="Correo verificado" className={adminInput}/><input name="linkedin_url" type="url" aria-label="Perfil LinkedIn" placeholder="URL personal de LinkedIn" className={adminInput}/><button disabled={busy} className={adminButtonSecondary}>Añadir persona</button></form></div>
  <div className={`${adminPanel} p-6`}><h3 className="text-lg font-semibold">Historial y evidencia</h3><form className="mt-4 grid gap-3 sm:grid-cols-2" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(await save({action:'event',company_id:company.id,channel:f.get('channel'),event_type:'manual_note',summary:f.get('summary'),source:'user_report',evidence_url:f.get('evidence_url')}))form.reset()}}><select name="channel" aria-label="Canal" className={adminInput}>{['email','linkedin','upwork','phone','form','chat','meeting'].map(v=><option key={v} value={v}>{v}</option>)}</select><input name="evidence_url" type="url" aria-label="Enlace de evidencia" placeholder="Enlace a correo, oferta o evidencia" className={adminInput}/><textarea name="summary" required aria-label="Resumen de interacción" placeholder="Qué ha sucedido y qué queda pendiente" className={`${adminInput} sm:col-span-2`} rows={2}/><button disabled={busy} className={adminButtonSecondary}>Registrar interacción</button></form><ol className="mt-6 space-y-4">{events.map(e=><li key={e.id} className="border-l-2 border-indigo-200 pl-4"><p className="text-xs text-slate-400">{date(e.occurred_at)} · {e.channel || 'chat'} · {e.source==='user_report'?'Confirmado por Arnau':e.source || 'Fuente sin indicar'}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{e.summary}</p>{safeUrl(e.evidence_url)&&<a href={safeUrl(e.evidence_url)} target="_blank" rel="noopener noreferrer" className="mt-2 inline-block text-xs font-semibold text-indigo-700">Ver evidencia ↗</a>}</li>)}</ol>{!events.length&&<p className="mt-5 text-sm text-slate-500">Sin interacciones registradas.</p>}</div></div>:<EmptyState>Selecciona una empresa para consultar su brief, personas, conversaciones y siguiente paso.</EmptyState>}</section></div>
 </>
}
