import { redirect } from 'next/navigation'
import AdminShell from '@/components/growth-admin/AdminShell'
import { Badge, PageHeader, SectionHeading, StatCard, adminButtonSecondary, adminPanel, statusTone } from '@/components/growth-admin/AdminUi'
import { getTasks, isGrowthAdminAuthenticated, queryGrowthTable } from '@/lib/growth-admin'
import { getLinkedInConnection, linkedInConnectionStatus } from '@/lib/growth-integrations'
import { getMetricsBundle } from '@/lib/growth-admin-performance'
import { gmailOAuthReadiness } from '@/lib/google-oauth-finance'

export const dynamic='force-dynamic'
export const revalidate=0

type IntegrationConnection={connection_id:string;provider:string;display_name?:string;updated_at?:string;metadata?:Record<string,unknown>|null}

export default async function SystemPage(){
  if(!(await isGrowthAdminAuthenticated())) redirect('/growth-admin/login')
  const [connection,tasks,metrics,calendlyRows]=await Promise.all([
    getLinkedInConnection(),
    getTasks(),
    getMetricsBundle(),
    queryGrowthTable<IntegrationConnection>('integration_connections',{tenant_id:'eq.sc-analytics',provider:'eq.calendly',order:'updated_at.desc',limit:'1'},{cacheSeconds:0}),
  ])
  const linkedin=linkedInConnectionStatus(connection)
  const linkedInBadge = linkedin.connected ? 'CONNECTED' : linkedin.expired ? 'EXPIRED' : 'ATTENTION'
  const googleReadiness=gmailOAuthReadiness()
  const googleConnected=Boolean(metrics.sources.google_connected)
  const calendly=calendlyRows[0]
  const calendlyTokenConfigured=Boolean((process.env.CALENDLY_ACCESS_TOKEN||'').trim())
  const calendlyConnected=Boolean(calendly)
  const apolloConfigured=Boolean((process.env.APOLLO_API_KEY||'').trim())
  const failed=tasks.filter(t=>t.status==='failed').slice(0,12)
  const lastEditorial=tasks.find(t=>t.type==='OPERATOR_EDITORIAL_RUN'||t.type==='EDITORIAL_RUN')
  const lastProspect=tasks.find(t=>t.type==='OPERATOR_PROSPECT'||t.type==='PROSPECT_RESEARCH')
  const calendlyLastSync=String(calendly?.metadata?.last_synced_at||calendly?.updated_at||'')

  return <AdminShell active="system">
    <PageHeader eyebrow="CRM · System" title="Integraciones" description="La infraestructura técnica pertenece al mismo Operating System. Aquí solo marcamos una integración como conectada cuando existe evidencia real de autorización o sincronización; configuración y conexión no se confunden."/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="LinkedIn" value={linkedin.connected?'Conectado':linkedin.expired?'Expirado':'Atención'} tone={linkedin.connected?'green':'amber'}/><StatCard label="Google / GA4" value={googleConnected?'Conectado':googleReadiness.configured?'OAuth pendiente':'Pendiente'} tone={googleConnected?'green':'amber'}/><StatCard label="Apollo" value={apolloConfigured?'Credencial presente':'Pendiente'} note={apolloConfigured?'La clave existe; el proveedor todavía debe validarse desde un flujo operativo.':'Sin credencial configurada.'} tone="amber"/><StatCard label="Calendly" value={calendlyConnected?'Conectado':calendlyTokenConfigured?'Listo para sync':'Pendiente'} tone={calendlyConnected?'green':'amber'}/></div>

    <section className="mt-12"><SectionHeading eyebrow="CRM · Data sources & actions" title="Conectores" description="Cada integración indica qué está realmente operativo, qué falta y qué módulo alimenta."/><div className="grid gap-5 xl:grid-cols-2">
      <article className={`${adminPanel} p-5`}><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">LinkedIn</p><h3 className="mt-2 text-lg font-semibold text-slate-950">{connection?.display_name||'Arnau Sastre'}</h3></div><Badge tone={linkedin.connected?'green':'amber'}>{linkedInBadge}</Badge></div><p className="mt-4 text-sm leading-6 text-slate-600">Publicación personal por API oficial. Analytics entra por XLS/XLSX oficial mientras Community Management API no esté disponible. Connect/follow/invite continúa human-in-the-loop.</p><p className="mt-3 text-xs text-slate-500">Scopes: {(connection?.scopes||[]).join(', ')||'—'}</p><div className="mt-4 flex gap-2"><a href="/api/linkedin/connect" className={adminButtonSecondary}>Reconectar</a><a href="/growth-admin/analytics" className={adminButtonSecondary}>Analytics</a></div></article>
      <article className={`${adminPanel} p-5`}><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Google Analytics 4 + Search Console</p><h3 className="mt-2 text-lg font-semibold text-slate-950">SC-Analytics Website</h3></div><Badge tone={googleConnected?'green':'amber'}>{googleConnected?'CONNECTED':googleReadiness.configured?'OAUTH PENDING':'CONFIG PENDING'}</Badge></div><p className="mt-4 text-sm leading-6 text-slate-600">El tracking web puede existir independientemente de la conexión de reporting. Este estado refleja si el CRM puede leer y sincronizar GA4/Search Console, no solo si la web envía eventos.</p><div className="mt-4 flex gap-2">{googleConnected?<a href="/growth-admin/analytics" className={adminButtonSecondary}>Ver Analytics</a>:googleReadiness.configured?<a href="/api/growth-admin/google/connect?account=corporate&return_to=/growth-admin/system" className={adminButtonSecondary}>Autorizar Google</a>:<a href="/growth-admin/finance/integrations" className={adminButtonSecondary}>Revisar configuración</a>}</div></article>
      <article className={`rounded-2xl border p-5 ${apolloConfigured?'border-sky-200 bg-sky-50':'border-amber-200 bg-amber-50'}`}><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Apollo</p><h3 className="mt-2 text-lg font-semibold text-slate-950">Prospecting & enrichment</h3></div><Badge tone={apolloConfigured?'blue':'amber'}>{apolloConfigured?'KEY PRESENT':'PENDING'}</Badge></div><p className="mt-4 text-sm leading-6 text-slate-600">{apolloConfigured?'Hay credencial disponible, pero no lo marcamos como conectado hasta que un flujo de enrichment la valide y escriba datos trazables en Companies/People.':'Se conectará como proveedor de empresas/personas. Los resultados alimentarán Companies + People + acciones recomendadas; no será un CRM paralelo.'}</p><a href="/growth-admin/crm" className="mt-4 inline-block text-xs font-semibold text-indigo-600">Ver motor comercial →</a></article>
      <article className={`rounded-2xl border p-5 ${calendlyConnected?'border-emerald-200 bg-emerald-50':'border-amber-200 bg-amber-50'}`}><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Calendly</p><h3 className="mt-2 text-lg font-semibold text-slate-950">Discovery calls</h3></div><Badge tone={calendlyConnected?'green':'amber'}>{calendlyConnected?'CONNECTED':calendlyTokenConfigured?'READY TO SYNC':'PENDING'}</Badge></div><p className="mt-4 text-sm leading-6 text-slate-600">{calendlyConnected?'La sincronización enlaza bookings con personas, oportunidades y reuniones; además mantiene el webhook de altas/cancelaciones.':calendlyTokenConfigured?'El token está configurado. Ejecuta una sincronización desde Clientes o Partners para validar la cuenta, importar reuniones recientes y registrar el webhook.':'Falta CALENDLY_ACCESS_TOKEN antes de poder sincronizar.'}</p>{calendlyLastSync&&<p className="mt-3 text-xs text-slate-500">Última sincronización: {new Date(calendlyLastSync).toLocaleString('es-ES',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Madrid'})}</p>}<div className="mt-4 flex gap-2"><a href="/growth-admin/crm" className={adminButtonSecondary}>{calendlyConnected?'Ver reuniones':'Ir a Clientes'}</a></div></article>
    </div></section>

    <section className="mt-14"><SectionHeading eyebrow="CRM · Automation" title="Workers y últimas ejecuciones"/><div className="grid gap-4 md:grid-cols-3"><div className={`${adminPanel} p-4`}><p className="text-xs text-slate-500">Operator Queue</p><p className="mt-2 font-semibold text-slate-950">Cada 5 min + dispatch inmediato</p><p className="mt-1 text-xs text-slate-500">Generación, rewrite, prospecting, intelligence, competencia y publish-now. El barrido periódico recupera tareas si falla el dispatch inmediato.</p></div><div className={`${adminPanel} p-4`}><p className="text-xs text-slate-500">Website Publisher</p><p className="mt-2 font-semibold text-slate-950">Cada 15 min</p><p className="mt-1 text-xs text-slate-500">Ejecuta artículos aprobados cuando vencen.</p></div><div className={`${adminPanel} p-4`}><p className="text-xs text-slate-500">LinkedIn Publisher</p><p className="mt-2 font-semibold text-slate-950">Horario programado</p><p className="mt-1 text-xs text-slate-500">Solo LinkedIn aprobado y due.</p></div></div><div className="mt-4 flex flex-wrap gap-2">{lastEditorial&&<Badge tone={statusTone(lastEditorial.status)}>Editorial: {lastEditorial.status}</Badge>}{lastProspect&&<Badge tone={statusTone(lastProspect.status)}>Prospecting: {lastProspect.status}</Badge>}</div></section>

    <section className="mt-14 pb-12"><SectionHeading eyebrow="CRM · Errors" title="Fallos recientes" count={failed.length}/>{failed.length===0?<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-800">No hay tareas fallidas en el historial reciente.</div>:<div className="space-y-3">{failed.map(t=><a key={t.task_id} href={`/growth-admin/operations?task=${encodeURIComponent(t.task_id)}#task-${encodeURIComponent(t.task_id)}`} className="block rounded-2xl border border-rose-200 bg-rose-50 p-4 transition hover:border-rose-300"><div className="flex justify-between gap-4"><p className="text-sm font-semibold text-slate-950">{t.type}</p><Badge tone="rose">failed</Badge></div><p className="mt-2 line-clamp-3 text-xs leading-5 text-rose-700">{JSON.stringify(t.outputs||{})}</p><p className="mt-2 text-[10px] font-semibold text-rose-700">Abrir trazabilidad →</p></a>)}</div>}</section>
  </AdminShell>
}
