import { redirect } from 'next/navigation'
import AdminShell from '@/components/growth-admin/AdminShell'
import { Badge, PageHeader, SectionHeading, StatCard, adminButtonSecondary, adminPanel, statusTone } from '@/components/growth-admin/AdminUi'
import { getTasks, isGrowthAdminAuthenticated } from '@/lib/growth-admin'
import { getLinkedInConnection, linkedInConnectionStatus } from '@/lib/growth-integrations'

export const dynamic='force-dynamic'
export const revalidate=0

export default async function SystemPage(){
  if(!(await isGrowthAdminAuthenticated())) redirect('/growth-admin/login')
  const [connection,tasks]=await Promise.all([getLinkedInConnection(),getTasks()])
  const linkedin=linkedInConnectionStatus(connection)
  const linkedInBadge = linkedin.connected ? 'CONNECTED' : linkedin.expired ? 'EXPIRED' : 'ATTENTION'
  const failed=tasks.filter(t=>t.status==='failed').slice(0,12)
  const lastEditorial=tasks.find(t=>t.type==='OPERATOR_EDITORIAL_RUN'||t.type==='EDITORIAL_RUN')
  const lastProspect=tasks.find(t=>t.type==='OPERATOR_PROSPECT'||t.type==='PROSPECT_RESEARCH')

  return <AdminShell active="system">
    <PageHeader eyebrow="CRM · System" title="Integraciones" description="La infraestructura técnica también pertenece al mismo Operating System. Un conector solo se considera útil cuando alimenta una rama concreta del CRM o ejecuta una acción trazable."/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="LinkedIn" value={linkedin.connected?'Conectado':'Atención'} tone={linkedin.connected?'green':'amber'}/><StatCard label="GA4" value="Activo" note="G-3E1DK7935G" tone="green"/><StatCard label="Apollo" value="Pendiente" tone="amber"/><StatCard label="Calendly" value="Pendiente" tone="amber"/></div>

    <section className="mt-12"><SectionHeading eyebrow="CRM · Data sources & actions" title="Conectores" description="Cada integración debe tener un propósito operativo claro y una rama de destino dentro del CRM."/><div className="grid gap-5 xl:grid-cols-2">
      <article className={`${adminPanel} p-5`}><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">LinkedIn</p><h3 className="mt-2 text-lg font-semibold text-slate-950">{connection?.display_name||'Arnau Sastre'}</h3></div><Badge tone={linkedin.connected?'green':'amber'}>{linkedInBadge}</Badge></div><p className="mt-4 text-sm leading-6 text-slate-600">Publicación personal por API oficial. Analytics entra por XLS/XLSX oficial mientras Community Management API no esté disponible. Connect/follow/invite continúa human-in-the-loop.</p><p className="mt-3 text-xs text-slate-500">Scopes: {(connection?.scopes||[]).join(', ')||'—'}</p><div className="mt-4 flex gap-2"><a href="/api/linkedin/connect" className={adminButtonSecondary}>Reconectar</a><a href="/growth-admin/analytics" className={adminButtonSecondary}>Analytics</a></div></article>
      <article className={`${adminPanel} p-5`}><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Google Analytics 4</p><h3 className="mt-2 text-lg font-semibold text-slate-950">SC-Analytics Website</h3></div><Badge tone="green">TRACKING ACTIVE</Badge></div><p className="mt-4 text-sm leading-6 text-slate-600">Page views + funnel events están instrumentados. Para importar reporting al CRM faltan el Property ID numérico y la credencial de Google Analytics Data API.</p><div className="mt-4 flex flex-wrap gap-2">{['article_view','50%','90%','contact','discovery','Calendly open'].map(v=><Badge key={v} tone="blue">{v}</Badge>)}</div></article>
      <article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Apollo</p><h3 className="mt-2 text-lg font-semibold text-slate-950">Prospecting & enrichment</h3></div><Badge tone="amber">PENDING</Badge></div><p className="mt-4 text-sm leading-6 text-slate-600">Se conectará como proveedor de empresas/personas. Los resultados alimentarán Companies + People + acciones recomendadas; no será un CRM paralelo.</p><a href="/growth-admin/crm" className="mt-4 inline-block text-xs font-semibold text-indigo-600">Ver comercial preparado →</a></article>
      <article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Calendly</p><h3 className="mt-2 text-lg font-semibold text-slate-950">Discovery calls</h3></div><Badge tone="amber">PENDING</Badge></div><p className="mt-4 text-sm leading-6 text-slate-600">El modelo CRM de reuniones ya existe. El webhook futuro convertirá booking → person/company/opportunity y permitirá medir <code>calendly_booked</code> de forma real.</p></article>
    </div></section>

    <section className="mt-14"><SectionHeading eyebrow="CRM · Automation" title="Workers y últimas ejecuciones"/><div className="grid gap-4 md:grid-cols-3"><div className={`${adminPanel} p-4`}><p className="text-xs text-slate-500">Operator Queue</p><p className="mt-2 font-semibold text-slate-950">Cada 5 min</p><p className="mt-1 text-xs text-slate-500">Generación, rewrite, prospecting, publish-now.</p></div><div className={`${adminPanel} p-4`}><p className="text-xs text-slate-500">Website Publisher</p><p className="mt-2 font-semibold text-slate-950">Cada 15 min</p><p className="mt-1 text-xs text-slate-500">Ejecuta artículos aprobados cuando vencen.</p></div><div className={`${adminPanel} p-4`}><p className="text-xs text-slate-500">LinkedIn Publisher</p><p className="mt-2 font-semibold text-slate-950">Horario existente</p><p className="mt-1 text-xs text-slate-500">Solo LinkedIn aprobado y due.</p></div></div><div className="mt-4 flex flex-wrap gap-2">{lastEditorial&&<Badge tone={statusTone(lastEditorial.status)}>Editorial: {lastEditorial.status}</Badge>}{lastProspect&&<Badge tone={statusTone(lastProspect.status)}>Prospecting: {lastProspect.status}</Badge>}</div></section>

    <section className="mt-14 pb-12"><SectionHeading eyebrow="CRM · Errors" title="Fallos recientes" count={failed.length}/>{failed.length===0?<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-800">No hay tareas fallidas en el historial reciente.</div>:<div className="space-y-3">{failed.map(t=><div key={t.task_id} className="rounded-2xl border border-rose-200 bg-rose-50 p-4"><div className="flex justify-between gap-4"><p className="text-sm font-semibold text-slate-950">{t.type}</p><Badge tone="rose">failed</Badge></div><p className="mt-2 line-clamp-3 text-xs leading-5 text-rose-700">{JSON.stringify(t.outputs||{})}</p></div>)}</div>}</section>
  </AdminShell>
}
