/* eslint-disable @typescript-eslint/no-explicit-any */
import { redirect } from 'next/navigation'
import AdminShell from '@/components/growth-admin/AdminShell'
import FinanceNav from '@/components/growth-admin/FinanceNav'
import { Badge, EmptyState, PageHeader, SectionHeading, adminButtonPrimary, adminButtonSecondary, adminInput, adminPanel, statusTone } from '@/components/growth-admin/AdminUi'
import { isGrowthAdminAuthenticated } from '@/lib/growth-admin'
import { getFinanceBundle } from '@/lib/growth-admin-performance'

export const dynamic='force-dynamic'
const n=(value:unknown)=>Number(value||0)
const money=(value:unknown,currency='EUR')=>`${n(value).toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})} ${currency}`

export default async function CashPage(){
  if(!(await isGrowthAdminAuthenticated())) redirect('/growth-admin/login')
  const bundle=await getFinanceBundle()
  const proposed=bundle.reconciliations.filter((r)=>r.status==='proposed')
  const paymentByBankTx=new Map(bundle.payments.filter((p)=>p.bank_transaction_id).map((p)=>[String(p.bank_transaction_id),p]))
  const txById=new Map(bundle.bank_transactions.map((t)=>[String(t.bank_transaction_id),t]))
  const invoiceById=new Map(bundle.invoices.map((i)=>[String(i.invoice_id),i]))
  const expenseById=new Map(bundle.expenses.map((e)=>[String(e.expense_id),e]))
  return <AdminShell active="finance">
    <PageHeader eyebrow="Finanzas · Treasury" title="Caja y banco" description="Cobros y pagos manuales, transacciones bancarias y conciliación con confirmación humana. Revolut nunca recibe permisos para mover dinero desde este módulo." actions={bundle.revolut_connections.length?<form action="/api/growth-admin/revolut/sync" method="post"><input type="hidden" name="days" value="90"/><button className="rounded-lg border border-white/20 bg-white/10 px-4 py-2.5 text-sm font-semibold text-white hover:bg-white/15">Sincronizar Revolut</button></form>:undefined}/>
    <FinanceNav active="/growth-admin/finance/cash"/>

    <section><SectionHeading eyebrow="Entrada manual" title="Registrar cobro o pago" description="Todo movimiento manual queda pendiente de doble check y puede vincularse a factura o gasto."/><form action="/api/growth-admin/finance" method="post" className={`${adminPanel} grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-4`}>
      <input type="hidden" name="type" value="payment"/><input type="hidden" name="return_to" value="/growth-admin/finance/cash"/>
      <select name="direction" className={adminInput}><option value="inflow">Cobro</option><option value="outflow">Pago</option></select>
      <select name="invoice_id" className={adminInput}><option value="">Factura opcional</option>{bundle.invoices.filter((i)=>!['paid','void','cancelled'].includes(String(i.status||''))).map((i)=><option key={i.invoice_id} value={String(i.invoice_id)}>{i.invoice_number||i.invoice_id} · {money(i.total,i.currency||'EUR')}</option>)}</select>
      <select name="expense_id" className={adminInput}><option value="">Gasto opcional</option>{bundle.expenses.filter((e)=>e.status!=='paid').map((e)=><option key={e.expense_id} value={String(e.expense_id)}>{e.vendor||e.expense_id} · {money(e.total,e.currency||'EUR')}</option>)}</select>
      <input required type="date" name="payment_date" className={adminInput}/><select name="currency" className={adminInput}><option>EUR</option><option>USD</option></select><input required type="number" step="0.01" min="0" name="amount" placeholder="Importe" className={adminInput}/><input type="number" step="0.000001" name="fx_rate" placeholder="Cambio a EUR si USD" className={adminInput}/><input name="method" placeholder="Banco / método" className={adminInput}/><input name="reference" placeholder="Referencia" className={`${adminInput} md:col-span-2 xl:col-span-3`}/><button className={adminButtonPrimary}>Registrar movimiento</button>
    </form></section>

    <section className="mt-14"><SectionHeading eyebrow="Bank matching" title="Conciliaciones propuestas" description="El sistema puede sugerir coincidencias por referencia e importe, pero no las confirma automáticamente." count={proposed.length}/>{proposed.length===0?<EmptyState>Sin conciliaciones pendientes. Cuando conectes Revolut, aparecerán aquí las coincidencias propuestas.</EmptyState>:<div className="space-y-3">{proposed.map((r)=>{const tx=txById.get(String(r.bank_transaction_id)); const entity=r.entity_type==='invoice'?invoiceById.get(String(r.entity_id)):expenseById.get(String(r.entity_id)); return <div key={r.reconciliation_id} className={`${adminPanel} p-5`}><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-950">{tx?.direction==='inflow'?'Ingreso':'Salida'} {money(r.matched_amount,r.currency||'EUR')}</p><Badge tone={Number(r.confidence||0)>=.95?'green':'amber'}>{Math.round(Number(r.confidence||0)*100)}% confianza</Badge></div><p className="mt-2 text-xs text-slate-500">Banco: {tx?.counterparty_name||'—'} · {tx?.reference||'Sin referencia'}</p><p className="mt-1 text-xs text-slate-500">Propuesta: {r.entity_type==='invoice'?'Factura':'Gasto'} · {entity?.invoice_number||entity?.vendor||r.entity_id}</p><p className="mt-1 text-[11px] text-slate-400">{r.notes||'Matching automático'}</p></div><div className="flex gap-2"><form action="/api/growth-admin/finance/reconciliation" method="post"><input type="hidden" name="reconciliation_id" value={String(r.reconciliation_id)}/><input type="hidden" name="action" value="confirm"/><button className={adminButtonPrimary}>Confirmar conciliación</button></form><form action="/api/growth-admin/finance/reconciliation" method="post"><input type="hidden" name="reconciliation_id" value={String(r.reconciliation_id)}/><input type="hidden" name="action" value="reject"/><button className={adminButtonSecondary}>Rechazar</button></form></div></div></div>})}</div>}
    </section>

    <section className="mt-14"><SectionHeading eyebrow="Bank feed" title="Transacciones bancarias" count={bundle.bank_transactions.length}/>{bundle.bank_transactions.length===0?<EmptyState>El feed bancario aparecerá cuando conectes Revolut Business en Integraciones.</EmptyState>:<div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-4 py-3">Fecha</th><th className="px-4 py-3">Contraparte</th><th className="px-4 py-3">Referencia</th><th className="px-4 py-3">Importe</th><th className="px-4 py-3">Conciliación</th></tr></thead><tbody>{bundle.bank_transactions.map((tx)=><tr key={tx.bank_transaction_id} className="border-t border-slate-200"><td className="px-4 py-3">{String(tx.booked_at||'').slice(0,10)||'—'}</td><td className="px-4 py-3 font-medium text-slate-800">{tx.counterparty_name||'—'}</td><td className="px-4 py-3 text-slate-500">{tx.reference||'—'}</td><td className={`px-4 py-3 font-semibold ${tx.direction==='inflow'?'text-emerald-700':'text-slate-900'}`}>{tx.direction==='outflow'?'-':'+'}{money(tx.amount,tx.currency||'EUR')}</td><td className="px-4 py-3"><Badge tone={tx.reconciliation_status==='matched'?'green':tx.reconciliation_status==='proposed'?'amber':'slate'}>{tx.reconciliation_status||'unmatched'}</Badge></td></tr>)}</tbody></table></div>}
    </section>

    <section className="mt-14 pb-12"><SectionHeading eyebrow="Cash ledger" title="Cobros y pagos registrados" count={bundle.payments.length}/>{bundle.payments.length===0?<EmptyState>Sin movimientos registrados.</EmptyState>:<div className="space-y-3">{bundle.payments.map((p)=>{const reviewed=['reviewed','confirmed'].includes(String(p.review_status||'')); return <div key={p.payment_id} className={`${adminPanel} flex flex-col gap-3 p-4 md:flex-row md:items-center md:justify-between`}><div><div className="flex gap-2"><Badge tone={p.direction==='inflow'?'green':'slate'}>{p.direction==='inflow'?'cobro':'pago'}</Badge><Badge tone={statusTone(String(p.status||''))}>{String(p.status||'recorded')}</Badge></div><p className="mt-2 text-sm font-semibold text-slate-900">{p.reference||p.method||'Movimiento'}</p><p className="text-xs text-slate-500">{p.payment_date||'—'} · {p.method||'Sin método'}</p></div><div className="flex items-center gap-3"><span className="font-semibold">{money(p.amount,p.currency||'EUR')}</span>{!reviewed&&p.source_system!=='revolut'&&<form action="/api/growth-admin/finance" method="post"><input type="hidden" name="type" value="review"/><input type="hidden" name="entity" value="payment"/><input type="hidden" name="entity_id" value={String(p.payment_id)}/><input type="hidden" name="decision" value="reviewed"/><input type="hidden" name="return_to" value="/growth-admin/finance/cash"/><button className={adminButtonSecondary}>✓ Doble check</button></form>}</div></div>})}</div>}
    </section>
  </AdminShell>
}
