import {redirect} from 'next/navigation'
import AdminShell from '@/components/growth-admin/AdminShell'
import {Badge,EmptyState,PageHeader,SectionHeading,adminButtonPrimary,adminInput,adminPanel,formatDate} from '@/components/growth-admin/AdminUi'
import {braveQuotaTone,getBraveQuota} from '@/lib/brave-quota'
import {isGrowthAdminAuthenticated,type GrowthTask} from '@/lib/growth-admin'
import {getWorkspaceEditorialBriefs,getWorkspaceEditorialTasks} from '@/lib/editorial-workspace'
export const dynamic='force-dynamic';export const revalidate=0

type Proposal={research_brief_id?:string}
export default async function ResearchPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  if(!(await isGrowthAdminAuthenticated()))redirect('/growth-admin/login')
  const params=await searchParams
  const[briefs,tasks,brave]=await Promise.all([getWorkspaceEditorialBriefs(),getWorkspaceEditorialTasks(),getBraveQuota()])
  const queued=typeof params.queued==='string'?params.queued:''
  const proposalTasks=tasks.filter((task:GrowthTask)=>task.type==='OPERATOR_EDITORIAL_PROPOSALS'&&task.status==='completed')
  const usedBriefIds=new Set(proposalTasks.flatMap(task=>Array.isArray(task.outputs?.proposals)?(task.outputs?.proposals as Proposal[]).map(row=>String(row.research_brief_id||'')).filter(Boolean):[]))
  const sourceCount=briefs.reduce((sum,brief)=>sum+(brief.research?.source_urls||[]).length,0)
  const quotaTone=braveQuotaTone(brave)
  const quotaLabel=!brave.configured?'Sin API key':!brave.available?'Sin lectura todavía':brave.monthlyRemaining===null?'Cuota sin dato':`${brave.monthlyRemaining.toLocaleString('es-ES')} restantes`
  return <AdminShell active="research">
    <PageHeader eyebrow="CRM · Editorial Intelligence" title="Research y briefs" description="Research descubre señales y fuentes; el evidence gate las convierte en briefs; Propuestas reutiliza esa biblioteca para no investigar dos veces lo mismo." actions={<a href="/growth-admin/content" className="rounded-lg bg-white px-4 py-2.5 text-sm font-semibold text-slate-950">Ir a Propuestas y Publicaciones</a>}/>
    {queued&&<div className="mb-5 rounded-xl border border-sky-200 bg-sky-50 p-4 text-sm text-sky-800">Proceso editorial encolado: {queued}.</div>}
    <section className="mb-6 grid gap-3 md:grid-cols-3"><div className={`${adminPanel} p-4`}><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">1 · Research</p><p className="mt-2 text-sm font-semibold text-slate-950">Señales + fuentes</p><p className="mt-1 text-xs leading-5 text-slate-500">Brave encuentra candidatos; se deduplican y se puntúan por relevancia, consecuencia y evidencia.</p></div><div className={`${adminPanel} p-4`}><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">2 · Biblioteca</p><p className="mt-2 text-sm font-semibold text-slate-950">{briefs.length} briefs · {sourceCount} fuentes</p><p className="mt-1 text-xs leading-5 text-slate-500">Los briefs quedan persistidos con tesis, problema de negocio, evidencia y URLs. No son temporales.</p></div><div className={`${adminPanel} p-4`}><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">3 · Propuestas</p><p className="mt-2 text-sm font-semibold text-slate-950">Reutilización automática</p><p className="mt-1 text-xs leading-5 text-slate-500">Al generar propuestas se consulta esta biblioteca. Si desarrollas una propuesta enlazada a un brief, se reutiliza su research sin otra barrida Brave.</p></div></section>
    <section className="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">Brave Search API</p><div className="mt-2 flex items-center gap-2"><Badge tone={quotaTone}>{quotaLabel}</Badge>{brave.monthlyLimit!==null&&<span className="text-xs text-slate-500">{brave.monthlyUsed?.toLocaleString('es-ES')||0} usadas de {brave.monthlyLimit.toLocaleString('es-ES')}</span>}</div></div><div className="text-xs text-slate-500">{brave.monthlyResetAt?<>Reinicio estimado: <strong>{formatDate(brave.monthlyResetAt,true)}</strong></>:brave.available?'Brave no informó una ventana mensual en la última respuesta.':'La primera búsqueda actualizará automáticamente la cuota reportada por Brave.'}{brave.updatedAt&&<span className="ml-2">· lectura {formatDate(brave.updatedAt,true)}</span>}</div></div></section>
    <section className="rounded-2xl border border-indigo-100 bg-indigo-50/60 p-5"><SectionHeading eyebrow="Discovery editorial" title="Descubrir temas editoriales" description="Puedes hacer una barrida abierta o investigar una URL concreta. La barrida evalúa candidatos y desarrolla solo los mejores briefs."/><div className="grid gap-4 xl:grid-cols-2"><form action="/api/growth-admin/operator-task" method="post" className={`${adminPanel} p-5`}><input type="hidden" name="action" value="editorial_run"/><input type="hidden" name="return_to" value="/growth-admin/research"/><input type="hidden" name="force_new" value="1"/><p className="text-sm font-semibold">Barrida editorial manual</p><textarea name="theme_hint" className={`mt-3 min-h-20 w-full ${adminInput}`} placeholder="Tema opcional; vacío = búsqueda transversal"/><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-[11px] font-medium text-slate-500">Máx. señales nuevas a evaluar<input type="number" min="1" max="100" name="max_signals" defaultValue="30" className={`mt-1 w-full ${adminInput}`}/><span className="mt-1 block text-[10px] leading-4 text-slate-400">30 = tope de candidatos nuevos que pueden guardarse y pasar por el scoring en esta ejecución.</span></label><label className="text-[11px] font-medium text-slate-500">Máx. briefs a desarrollar<input type="number" min="1" max="10" name="max_briefs" defaultValue="2" className={`mt-1 w-full ${adminInput}`}/><span className="mt-1 block text-[10px] leading-4 text-slate-400">2 = como máximo dos finalistas pasan a brief y generación de contenido en esta ejecución.</span></label></div><button className={`mt-4 ${adminButtonPrimary}`}>Ejecutar barrida</button></form><form action="/api/growth-admin/operator-task" method="post" className={`${adminPanel} p-5`}><input type="hidden" name="action" value="editorial_url"/><input type="hidden" name="return_to" value="/growth-admin/research"/><p className="text-sm font-semibold">Investigar una fuente concreta</p><p className="mt-1 text-xs leading-5 text-slate-500">Úsalo cuando ya tienes un artículo, estudio o noticia que quieres convertir en un brief con evidencia.</p><input type="url" name="url" required placeholder="https://..." className={`mt-3 w-full ${adminInput}`}/><input name="title" placeholder="Título opcional" className={`mt-2 w-full ${adminInput}`}/><button className={`mt-3 ${adminButtonPrimary}`}>Investigar fuente</button></form></div></section>
    <section className="mt-8 pb-12"><SectionHeading eyebrow="Biblioteca editorial" title="Ideas investigadas" description="Estos briefs son memoria editorial persistente. Propuestas los puede reutilizar y una publicación conserva su brief_id para mantener la trazabilidad hasta las fuentes." count={briefs.length}/><div className="space-y-3">{!briefs.length&&<EmptyState>Todavía no hay briefs investigados.</EmptyState>}{briefs.map(brief=>{const urls=brief.research?.source_urls||[],used=usedBriefIds.has(brief.brief_id);return <details key={brief.brief_id} className="rounded-xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer list-none"><div className="flex items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><Badge>{brief.family}</Badge><Badge tone="violet">{Number(brief.weighted_score||0).toFixed(1)}/10</Badge><Badge tone={used?'green':'blue'}>{used?'Usado en propuesta':'Disponible para propuestas'}</Badge><Badge>{urls.length} fuentes</Badge></div><h2 className="mt-3 text-base font-semibold">{brief.canonical_title}</h2></div><span className="text-xs font-semibold text-indigo-600">Abrir brief</span></div></summary><div className="mt-4 border-t border-slate-200 pt-4 text-sm text-slate-600"><p>{brief.thesis}</p>{brief.business_problem&&<p className="mt-2 text-xs"><strong>Problema:</strong> {brief.business_problem}</p>}<div className="mt-3 space-y-1">{urls.map((url,index)=><a key={url} href={url} target="_blank" rel="noreferrer" className="block truncate text-xs font-medium text-indigo-600">Fuente {index+1}: {url}</a>)}</div></div></details>})}</div></section>
  </AdminShell>
}
