import { redirect } from 'next/navigation'
import AdminShell from '@/components/growth-admin/AdminShell'
import { Badge, EmptyState, PageHeader, SectionHeading } from '@/components/growth-admin/AdminUi'
import { getRecentEditorialBriefs, isGrowthAdminAuthenticated } from '@/lib/growth-admin'

export const dynamic = 'force-dynamic'
export const revalidate = 0

export default async function ResearchPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  if (!(await isGrowthAdminAuthenticated())) redirect('/growth-admin/login')
  const params=await searchParams
  const briefs=await getRecentEditorialBriefs()
  const queued=typeof params.queued==='string'?params.queued:''

  return <AdminShell active="research">
    <PageHeader eyebrow="Editorial Intelligence" title="Research y briefs" description="Aquí no ves publicaciones: ves la tesis, la evidencia, el problema de negocio y la decisión editorial que alimentan el contenido." actions={<a href="/growth-admin/content" className="rounded-lg border border-slate-700 px-4 py-2.5 text-sm text-slate-300">Ver contenido generado</a>}/>
    {queued&&<div className="mb-6 rounded-xl border border-sky-900 bg-sky-950/30 p-4 text-sm text-sky-200">Research encolado: {queued}.</div>}

    <div className="grid gap-5 xl:grid-cols-2">
      <form action="/api/growth-admin/operator-task" method="post" className="rounded-2xl border border-slate-800 bg-slate-900/55 p-5"><input type="hidden" name="action" value="editorial_run"/><input type="hidden" name="return_to" value="/growth-admin/research"/><p className="text-sm font-semibold text-white">Barrida editorial manual</p><p className="mt-2 text-xs leading-5 text-slate-500">Busca señales actuales y deja que el gate editorial seleccione las mejores con evidencia.</p><textarea name="theme_hint" className="mt-4 min-h-20 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm" placeholder="Tema opcional; dejar vacío permite búsqueda diversificada."/><div className="mt-3 flex gap-2"><input type="number" name="max_signals" defaultValue="30" className="w-24 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><input type="number" name="max_briefs" defaultValue="2" className="w-20 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><button className="ml-auto rounded-lg bg-white px-4 py-2 text-sm font-semibold text-slate-950">Ejecutar</button></div></form>
      <form action="/api/growth-admin/operator-task" method="post" className="rounded-2xl border border-slate-800 bg-slate-900/55 p-5"><input type="hidden" name="action" value="editorial_url"/><input type="hidden" name="return_to" value="/growth-admin/research"/><p className="text-sm font-semibold text-white">Investigar una fuente concreta</p><p className="mt-2 text-xs leading-5 text-slate-500">Introduce una noticia, paper, informe o URL y pasa por el mismo evidence gate.</p><input type="url" name="url" required placeholder="https://..." className="mt-4 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><input name="title" placeholder="Título opcional" className="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"/><button className="mt-3 rounded-lg bg-white px-4 py-2 text-sm font-semibold text-slate-950">Investigar</button></form>
    </div>

    <section className="mt-10 pb-12"><SectionHeading eyebrow="Canonical briefs" title="Ideas investigadas" description="Puedes inspeccionar exactamente por qué merece contenido y de dónde sale cada afirmación." count={briefs.length}/><div className="space-y-4">{briefs.length===0&&<EmptyState>Todavía no hay briefs.</EmptyState>}{briefs.map((brief)=>{const sources=brief.research?.source_urls||[];return <details key={brief.brief_id} className="group rounded-2xl border border-slate-800 bg-slate-900/50 p-5"><summary className="cursor-pointer list-none"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap gap-2"><Badge>{brief.family}</Badge><Badge tone="violet">{Number(brief.weighted_score||0).toFixed(1)}/10</Badge><Badge>{brief.output_decision}</Badge><Badge>{brief.status}</Badge>{brief.visual?.needed&&<Badge tone="blue">visual: {brief.visual.type||'sí'}</Badge>}</div><h2 className="mt-4 text-lg font-semibold text-white">{brief.canonical_title}</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-400">{brief.thesis}</p></div><span className="text-xs text-sky-300">Abrir brief ↓</span></div></summary><div className="mt-5 grid gap-5 border-t border-slate-800 pt-5 lg:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Problema de negocio</p><p className="mt-2 text-sm leading-6 text-slate-300">{brief.business_problem||'—'}</p><p className="mt-5 text-xs font-semibold uppercase tracking-wide text-slate-500">Audiencia</p><p className="mt-2 text-sm text-slate-300">{(brief.target_audience||[]).join(', ')||'—'}</p></div><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Fuentes</p><div className="mt-2 flex flex-col gap-2">{sources.map((url,index)=><a key={url} href={url} target="_blank" rel="noreferrer" className="truncate text-sm text-sky-300">Fuente {index+1} ↗ · {url}</a>)}</div></div></div></details>})}</div></section>
  </AdminShell>
}
