import React from 'react'
import { BRAND } from './brand.mjs'
const h=React.createElement
function wrap(text,max=28,maxLines=4){const words=String(text||'').trim().split(/\s+/).filter(Boolean),out=[];let line='';for(let i=0;i<words.length;i++){const word=words[i],next=line?`${line} ${word}`:word;if(next.length>max&&line){out.push(line);line=word;if(out.length>=maxLines-1){if(i<words.length-1)line=`${line}…`;break}}else line=next}if(line&&out.length<maxLines)out.push(line);return out.slice(0,maxLines)}
function fittedSize(text,base,maxChars,maxLines,min){const length=String(text||'').length,capacity=maxChars*maxLines;if(length<=capacity*.72)return base;if(length<=capacity)return Math.round(base*.88);return Math.max(min,Math.round(base*.76))}
function TextBlock({text,x,y,fontSize,maxChars,maxLines=4,fill,weight=600,lineHeight=1.15,minSize=22}){const size=fittedSize(text,fontSize,maxChars,maxLines,minSize),wrapped=wrap(text,maxChars,maxLines);return h('text',{x,y,fill:fill||BRAND.text,fontFamily:BRAND.font,fontSize:size,fontWeight:weight},wrapped.map((line,i)=>h('tspan',{key:`${i}-${line}`,x,dy:i===0?0:Math.round(size*lineHeight)},line)))}
function palette(theme){const light=theme==='light';return{light,bg:light?'#F8FAFC':BRAND.background,bg2:light?'#EEF2F7':'#0A2031',text:light?'#0F172A':BRAND.text,muted:light?'#475569':BRAND.muted,line:light?'#CBD5E1':BRAND.line,panel:light?'#FFFFFF':BRAND.panel,panelAlt:light?'#EEF2FF':BRAND.panelAlt,accent:light?'#4338CA':BRAND.accent}}
function Frame({children,eyebrow='SC-ANALYTICS',logos,theme='dark'}){const p=palette(theme),logo=p.light?logos?.dark:logos?.white;return h('svg',{xmlns:'http://www.w3.org/2000/svg',width:BRAND.width,height:BRAND.height,viewBox:`0 0 ${BRAND.width} ${BRAND.height}`},h('defs',null,h('linearGradient',{id:'bg',x1:'0',y1:'0',x2:'1',y2:'1'},h('stop',{offset:'0%',stopColor:p.bg}),h('stop',{offset:'100%',stopColor:p.bg2}))),h('rect',{width:1200,height:1200,fill:'url(#bg)'}),h('path',{d:'M78 174 H1122 M78 1015 H1122',stroke:p.line,strokeWidth:2}),logo?h('image',{href:logo,x:78,y:62,width:330,height:96,preserveAspectRatio:'xMinYMid meet'}):h('text',{x:78,y:120,fill:p.text,fontFamily:BRAND.font,fontSize:34,fontWeight:700,letterSpacing:4},eyebrow),h('text',{x:78,y:1085,fill:p.muted,fontFamily:BRAND.font,fontSize:23},BRAND.footer),children)}
function Insight({spec,logos}){const p=palette(spec.theme);return h(Frame,{logos,theme:spec.theme,eyebrow:spec.eyebrow},h(TextBlock,{text:spec.headline,x:78,y:330,fontSize:76,maxChars:24,maxLines:4,minSize:48,fill:p.text,weight:700}),spec.subheadline&&h(TextBlock,{text:spec.subheadline,x:82,y:735,fontSize:32,maxChars:48,maxLines:3,minSize:24,fill:p.muted,weight:400}),h('rect',{x:82,y:914,width:190,height:7,rx:3,fill:p.accent}))}
function Statement({spec,logos}){const p=palette(spec.theme);return h(Frame,{logos,theme:spec.theme,eyebrow:spec.eyebrow},h('rect',{x:78,y:250,width:1044,height:610,rx:34,fill:p.panel,stroke:p.line,strokeWidth:2}),h(TextBlock,{text:spec.headline,x:124,y:365,fontSize:82,maxChars:22,maxLines:4,minSize:50,fill:p.text,weight:720}),spec.subheadline&&h(TextBlock,{text:spec.subheadline,x:126,y:735,fontSize:30,maxChars:48,maxLines:2,minSize:23,fill:p.muted,weight:400}))}
function MetricCase({spec,logos}){const p=palette(spec.theme),metrics=(spec.metrics||[]).slice(0,3);return h(Frame,{logos,theme:spec.theme,eyebrow:spec.eyebrow},h(TextBlock,{text:spec.headline,x:78,y:270,fontSize:54,maxChars:34,maxLines:2,minSize:40,fill:p.text}),metrics.map((m,i)=>{const y=455+i*168;return h('g',{key:`${m.label}-${i}`},h('rect',{x:78,y:y-62,width:1044,height:130,rx:24,fill:i===0?p.panelAlt:p.panel,stroke:p.line,strokeWidth:1.5}),h('text',{x:116,y:y+16,fill:p.accent,fontFamily:BRAND.font,fontSize:64,fontWeight:750},String(m.value||'')),h(TextBlock,{text:m.label,x:425,y:y-4,fontSize:27,maxChars:38,maxLines:2,minSize:21,fill:p.muted,weight:450}))}),h('text',{x:78,y:986,fill:p.muted,fontFamily:BRAND.font,fontSize:19},spec.note||''))}
function ProcessFlow({spec,logos}){const p=palette(spec.theme),steps=(spec.steps||[]).slice(0,5);return h(Frame,{logos,theme:spec.theme,eyebrow:spec.eyebrow},h(TextBlock,{text:spec.headline,x:78,y:270,fontSize:53,maxChars:34,maxLines:2,minSize:40,fill:p.text}),steps.map((step,i)=>{const y=402+i*115;return h('g',{key:`${step}-${i}`},h('rect',{x:126,y:y-44,width:948,height:82,rx:20,fill:i===steps.length-1?p.panelAlt:p.panel,stroke:i===steps.length-1?p.accent:p.line,strokeWidth:2}),h('circle',{cx:176,cy:y-3,r:18,fill:p.accent}),h('text',{x:176,y:y+4,fill:p.bg,textAnchor:'middle',fontFamily:BRAND.font,fontSize:17,fontWeight:700},String(i+1)),h(TextBlock,{text:step,x:222,y:y+7,fontSize:29,maxChars:54,maxLines:1,minSize:22,fill:p.text,weight:i===steps.length-1?650:500}))}))}
function Comparison({spec,logos}){const p=palette(spec.theme),left=spec.left||{},right=spec.right||{};const card=(x,label,text,accent)=>h('g',null,h('rect',{x,y:365,width:475,height:485,rx:30,fill:p.panel,stroke:accent?p.accent:p.line,strokeWidth:2}),h('text',{x:x+40,y:428,fill:accent?p.accent:p.muted,fontFamily:BRAND.font,fontSize:19,letterSpacing:2.2},label),h(TextBlock,{text,x:x+40,y:530,fontSize:40,maxChars:19,maxLines:5,minSize:27,fill:p.text,weight:600}));return h(Frame,{logos,theme:spec.theme,eyebrow:spec.eyebrow},h(TextBlock,{text:spec.title||'A better business question',x:78,y:265,fontSize:52,maxChars:35,maxLines:2,minSize:40,fill:p.text}),card(78,left.label||'COMMON FRAMING',left.text||'',false),card(647,right.label||'BETTER QUESTION',right.text||'',true))}
export function renderVisual(spec,logos){const template=String(spec.template||'insight');if(template==='metric_case')return h(MetricCase,{spec,logos});if(template==='process_flow')return h(ProcessFlow,{spec,logos});if(template==='comparison')return h(Comparison,{spec,logos});if(template==='statement')return h(Statement,{spec,logos});return h(Insight,{spec,logos})}
