import { redirect } from 'next/navigation'
import AdminShell from '@/components/growth-admin/AdminShell'
import CopyButton from '@/components/growth-admin/CopyButton'
import { Badge, EmptyState, PageHeader, SectionHeading, StatCard, statusTone } from '@/components/growth-admin/AdminUi'
import { getInteractions, getMeetings, getOpportunities, getPeople, getReadyManualActions, getTasks, getTopCompanies, isGrowthAdminAuthenticated } from '@/lib/growth-admin'

export const dynamic = 'force-dynamic'
export const revalidate = 0

export default async function CrmPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  if (!(await isGrowthAdminAuthenticated())) redirect('/growth-admin/login')
  const params = await searchParams
  const [companies,people,actions,interactions,opportunities,meetings,tasks] = await Promise.all([getTopCompanies(),getPeople(),getReadyManualActions(),getInteractions(),getOpportunities(),getMeetings(),getTasks()])
  const companyById = new Map(companies.map((row)=>[row.company_id,row]))
  const queued = typeof params.queued==='string'?params.queued:''
  const prospectTasks = tasks.filter((task)=>task.type==='OPERATOR_PROSPECT').slice(0,6)

  return <AdminShell active="crm">
    <PageHeader eyebrow="Commercial OS" title="CRM y prospecting" description="Empresas, personas, acciones LinkedIn, conversaciones, reuniones y oportunidades en una misma capa. Apollo se conectará aquí como proveedor de discovery/enrichment; Supabase seguirá siendo la fuente de verdad." actions={<form action="/api/growth-admin/operator-task" method="post"><input type="hidden" name="action" value="prospect"/><input type="hidden" name="mode" value="lead"/><input type="hidden" name="limit" value="10"/><input type="hidden" name="return_to" value="/growth-admin/crm"/><button className="rounded-lg bg-white px-4 py-2.5 text-sm font-semibold text-slate-950">Buscar 10 leads ahora</button></form>}/>
    {queued&&<div className="mb-6 rounded-xl border border-sky-900 bg-sky-950/30 p-4 text-sm text-sky-200">Prospecting encolado ({queued}). El resultado aparecerá aquí cuando termine el worker.</div>}

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Empresas" value={companies.length}/><StatCard label="Personas" value={people.length}/><StatCard label="Acciones listas" value={actions.length} tone="violet"/><StatCard label="Oportunidades" value={opportunities.length} tone="green"/><StatCard label="Reuniones" value={meetings.length} tone="blue"/></div>

    <section className="mt-10"><SectionHeading eyebrow="LinkedIn human-in-the-loop" title="Checklist para ejecutar" description="El sistema prepara a quién contactar y el mensaje; tú ejecutas la acción. Si algún día disponemos de un identificador de mensajería fiable, añadiremos apertura directa del composer; por ahora el perfil es el fallback seguro." count={actions.length}/><div className="space-y-4">{actions.length===0&&<EmptyState>No hay acciones manuales aprobadas ahora mismo. Ejecuta prospecting o aprueba una acción comercial para que aparezca aquí.</EmptyState>}{actions.map((action)=>{const payload=action.payload||{};const person=payload.person;const msg=typeof payload.message==='string'?payload.message:'';const company=typeof payload.company==='string'?payload.company:'';return <article key={action.approval_id} className="rounded-2xl border border-slate-800 bg-slate-900/55 p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex flex-wrap gap-2"><Badge tone="violet">{action.action_type}</Badge>{company&&<Badge>{company}</Badge>}</div><h3 className="mt-3 font-semibold text-white">{person?.name||action.summary}</h3>{person?.role&&<p className="mt-1 text-sm text-slate-500">{person.role}</p>}{msg&&<div className="mt-4 max-w-3xl whitespace-pre-wrap rounded-xl border border-slate-800 bg-slate-950/70 p-4 text-sm leading-6 text-slate-300">{msg}</div>}</div><div className="flex shrink-0 flex-wrap gap-2">{person?.linkedin_url&&<a href={person.linkedin_url} target="_blank" rel="noreferrer" className="rounded-lg border border-sky-800 px-3 py-2 text-xs text-sky-300">Abrir perfil ↗</a>}{!person?.linkedin_url&&typeof payload.linkedin_search_url==='string'&&payload.linkedin_search_url&&<a href={payload.linkedin_search_url} target="_blank" rel="noreferrer" className="rounded-lg border border-sky-800 px-3 py-2 text-xs text-sky-300">Buscar LinkedIn ↗</a>}{msg&&<CopyButton text={msg}/>}<form action="/api/growth-admin/mark-executed" method="post"><input type="hidden" name="approval_id" value={action.approval_id}/><button className="rounded-lg bg-white px-3 py-2 text-xs font-semibold text-slate-950">Marcar ejecutado</button></form></div></div></article>})}</div></section>

    <section className="mt-12"><div className="grid gap-6 xl:grid-cols-2"><div><SectionHeading eyebrow="Arnau Sastre" title="Personas objetivo" description="Candidatos para seguir, conectar o contactar desde el perfil personal." count={people.length}/><div className="space-y-3">{people.length===0&&<EmptyState>Aún no hay personas. El prospecting público actual puede empezar a llenar esta cola; Apollo la enriquecerá después.</EmptyState>}{people.slice(0,30).map((person)=>{const company=person.company_id?companyById.get(person.company_id):undefined;return <article key={person.person_id} className="rounded-xl border border-slate-800 bg-slate-900/45 p-4"><div className="flex items-start justify-between gap-4"><div><p className="font-medium text-white">{person.name||'Persona por identificar'}</p><p className="mt-1 text-sm text-slate-500">{person.role||'Rol desconocido'}{company?` · ${company.name}`:''}</p><div className="mt-2 flex gap-2"><Badge>{person.status||'candidate'}</Badge>{person.relevance_score&&<Badge tone="violet">fit {Number(person.relevance_score).toFixed(1)}</Badge>}</div></div>{person.linkedin_url?<a href={person.linkedin_url} target="_blank" rel="noreferrer" className="rounded-lg border border-sky-800 px-3 py-2 text-xs text-sky-300">LinkedIn ↗</a>:person.public_source_url?<a href={person.public_source_url} target="_blank" rel="noreferrer" className="text-xs text-slate-400">Fuente ↗</a>:null}</div></article>})}</div></div>
      <div><SectionHeading eyebrow="SC-Analytics" title="Invitaciones a seguir la página" description="La futura cola Apollo separará candidatos de página de las conexiones personales. La ejecución de invites seguirá manual mientras LinkedIn no ofrezca una vía oficial adecuada."/><div className="rounded-2xl border border-dashed border-slate-800 bg-slate-950/30 p-7 text-sm leading-6 text-slate-500"><p className="font-semibold text-slate-300">Cola separada preparada conceptualmente.</p><p className="mt-2">Cuando Apollo esté conectado clasificaremos persona → ICP → acción recomendada: seguir/conectar desde Arnau o invitar a seguir SC-Analytics. No mezclaremos las dos intenciones.</p></div></div></div></section>

    <section className="mt-12"><SectionHeading eyebrow="Accounts" title="Empresas detectadas" count={companies.length}/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{companies.slice(0,36).map((company)=><article key={company.company_id} className="rounded-xl border border-slate-800 bg-slate-900/45 p-4"><div className="flex items-start justify-between gap-4"><div><p className="font-medium text-white">{company.name}</p><p className="mt-1 text-xs text-slate-500">{company.industry||'Industria desconocida'} · {company.country||'—'}</p></div><Badge tone="violet">{Number(company.score||0).toFixed(1)}</Badge></div><p className="mt-3 line-clamp-3 text-xs leading-5 text-slate-600">{company.score_reason}</p><div className="mt-3 flex gap-3 text-xs">{company.linkedin_url&&<a href={company.linkedin_url} target="_blank" className="text-sky-300">LinkedIn ↗</a>}{company.website&&<a href={company.website} target="_blank" className="text-slate-400">Web ↗</a>}</div></article>)}</div></section>

    <section className="mt-12"><div className="grid gap-6 xl:grid-cols-2"><div><SectionHeading eyebrow="Pipeline" title="Oportunidades" count={opportunities.length}/>{opportunities.length===0?<EmptyState>La tabla CRM ya existe. Cuando conectemos leads, discovery calls y propuestas, aparecerán aquí con valor, probabilidad y siguiente acción.</EmptyState>:<div className="space-y-3">{opportunities.map((op)=><div key={op.opportunity_id} className="rounded-xl border border-slate-800 p-4"><div className="flex justify-between"><p className="font-medium">{op.name}</p><Badge tone="green">{op.stage}</Badge></div><p className="mt-2 text-sm text-slate-500">{Number(op.value||0).toLocaleString('es-ES')} {op.currency} · {Number(op.probability||0)}%</p></div>)}</div>}</div><div><SectionHeading eyebrow="Calendly / reuniones" title="Meetings" count={meetings.length}/>{meetings.length===0?<EmptyState>Preparado para Calendly. Las reservas se vincularán a persona, empresa y oportunidad.</EmptyState>:<div className="space-y-3">{meetings.map((meeting)=><div key={meeting.meeting_id} className="rounded-xl border border-slate-800 p-4"><div className="flex justify-between"><p className="font-medium">{meeting.provider}</p><Badge tone={statusTone(meeting.status)}>{meeting.status}</Badge></div><p className="mt-2 text-xs text-slate-500">{meeting.starts_at||'Sin fecha'}</p></div>)}</div>}</div></div></section>

    <section className="mt-12 pb-12"><SectionHeading eyebrow="Activity" title="Interacciones recientes" count={interactions.length}/><div className="overflow-x-auto rounded-xl border border-slate-800"><table className="min-w-full text-left text-xs"><thead className="bg-slate-950 text-slate-600"><tr><th className="px-4 py-3">Canal</th><th className="px-4 py-3">Tipo</th><th className="px-4 py-3">Contenido</th><th className="px-4 py-3">Fecha</th></tr></thead><tbody>{interactions.slice(0,40).map((row)=><tr key={row.interaction_id} className="border-t border-slate-800 bg-slate-900/40"><td className="px-4 py-3">{row.channel||'—'}</td><td className="px-4 py-3">{row.kind||'—'}</td><td className="max-w-xl px-4 py-3 text-slate-400">{row.content||'—'}</td><td className="px-4 py-3 text-slate-600">{row.occurred_at||'—'}</td></tr>)}</tbody></table></div>{prospectTasks.length>0&&<div className="mt-4 flex flex-wrap gap-2">{prospectTasks.map((task)=><Badge key={task.task_id} tone={statusTone(task.status)}>{task.status}: prospecting</Badge>)}</div>}</section>
  </AdminShell>
}
